// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_logs.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :exec

INSERT INTO audit_logs (
    organization_id,
    user_id,
    action,
    entity_type,
    entity_id,
    old_data,
    new_data,
    ip_address,
    user_agent
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateAuditLogParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	Action         AuditAction `json:"action"`
	EntityType     string      `json:"entity_type"`
	EntityID       pgtype.UUID `json:"entity_id"`
	OldData        []byte      `json:"old_data"`
	NewData        []byte      `json:"new_data"`
	IpAddress      *netip.Addr `json:"ip_address"`
	UserAgent      *string     `json:"user_agent"`
}

// Audit log queries
// The audit_logs table is append-only: no UPDATE or DELETE is ever performed.
// Inserts one immutable audit record. Caller is responsible for satisfying
// the table CHECK constraints:
//   - create/update/delete/permission_change: entity_id must be non-NULL
//   - update: both old_data and new_data must be non-NULL
//   - login/logout: entity_id must be NULL
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog,
		arg.OrganizationID,
		arg.UserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.OldData,
		arg.NewData,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}
