// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO refresh_tokens (user_id, token_hash, expires_at, ip_address, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, token_hash, expires_at, revoked_at, ip_address, user_agent, created_at, successor_id
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	IpAddress *netip.Addr        `json:"ip_address"`
	UserAgent *string            `json:"user_agent"`
}

// Authentication queries
// Refresh token lifecycle management
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.SuccessorID,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE  expires_at <= $1
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens, expiresAt)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, revoked_at, ip_address, user_agent, created_at, successor_id
FROM   refresh_tokens
WHERE  token_hash = $1
LIMIT  1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.SuccessorID,
	)
	return i, err
}

const getRefreshTokenByHashForUpdate = `-- name: GetRefreshTokenByHashForUpdate :one
SELECT id, user_id, token_hash, expires_at, revoked_at, ip_address, user_agent, created_at, successor_id
FROM   refresh_tokens
WHERE  token_hash = $1
FOR UPDATE
`

func (q *Queries) GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHashForUpdate, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.SuccessorID,
	)
	return i, err
}

const revokeAndLinkSuccessor = `-- name: RevokeAndLinkSuccessor :execrows
UPDATE refresh_tokens
SET    revoked_at   = NOW(),
       successor_id = $2
WHERE  id           = $1
  AND  revoked_at   IS NULL
`

type RevokeAndLinkSuccessorParams struct {
	ID          pgtype.UUID `json:"id"`
	SuccessorID pgtype.UUID `json:"successor_id"`
}

// Atomically revokes a token and records the ID of its successor.
// Used exclusively during token rotation: the new token must be inserted first
// so its ID is available as $2. Returns the number of rows affected; the caller
// must assert exactly 1 (enforced by the FOR UPDATE lock held on the old token).
func (q *Queries) RevokeAndLinkSuccessor(ctx context.Context, arg RevokeAndLinkSuccessorParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAndLinkSuccessor, arg.ID, arg.SuccessorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET    revoked_at = NOW()
WHERE  id = $1
  AND  revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :exec
UPDATE refresh_tokens
SET    revoked_at = NOW()
WHERE  user_id = $1
  AND  revoked_at IS NULL
`

func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeUserRefreshTokens, userID)
	return err
}
