// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verification_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :one

INSERT INTO email_verification_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreateEmailVerificationTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Email verification token queries
func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, createEmailVerificationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredEmailVerificationTokens = `-- name: DeleteExpiredEmailVerificationTokens :exec
DELETE FROM email_verification_tokens
WHERE  expires_at <= $1
`

// Removes tokens that have passed their expiry. Called by the background
// cleanup job. Unused expired tokens are safe to delete: they can never
// be consumed again.
func (q *Queries) DeleteExpiredEmailVerificationTokens(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredEmailVerificationTokens, expiresAt)
	return err
}

const getEmailVerificationTokenByHash = `-- name: GetEmailVerificationTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM   email_verification_tokens
WHERE  token_hash = $1
LIMIT  1
`

func (q *Queries) GetEmailVerificationTokenByHash(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenByHash, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailVerificationTokenByHashForUpdate = `-- name: GetEmailVerificationTokenByHashForUpdate :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM   email_verification_tokens
WHERE  token_hash = $1
FOR UPDATE
`

// Acquires a row-level exclusive lock on the token row.
// Used by VerifyEmailTransaction to serialize concurrent consumption attempts:
// the second concurrent call blocks here until the first transaction commits,
// then reads used_at IS NOT NULL and returns ErrVerificationTokenUsed.
// This enforces the single-use guarantee transactionally.
func (q *Queries) GetEmailVerificationTokenByHashForUpdate(ctx context.Context, tokenHash string) (EmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenByHashForUpdate, tokenHash)
	var i EmailVerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const useAllUserEmailVerificationTokens = `-- name: UseAllUserEmailVerificationTokens :exec
UPDATE email_verification_tokens
SET    used_at = NOW()
WHERE  user_id = $1
  AND  used_at IS NULL
`

// Invalidates all unused verification tokens for a user before a new one is
// issued. Prevents token accumulation (P2-5): without this, every resend
// call leaves an additional valid token in the table that could be consumed
// by a confused user or leaked in email logs.
func (q *Queries) UseAllUserEmailVerificationTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, useAllUserEmailVerificationTokens, userID)
	return err
}

const useEmailVerificationToken = `-- name: UseEmailVerificationToken :exec
UPDATE email_verification_tokens
SET    used_at = NOW()
WHERE  id      = $1
  AND  used_at IS NULL
`

// Marks a token as consumed. The AND used_at IS NULL guard prevents a
// double-use race condition from silently succeeding.
func (q *Queries) UseEmailVerificationToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, useEmailVerificationToken, id)
	return err
}
