// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fixturegen.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMatchesForTournament = `-- name: CountMatchesForTournament :one
SELECT COUNT(*)
FROM   matches
WHERE  tournament_id   = $1
  AND  organization_id = $2
`

type CountMatchesForTournamentParams struct {
	TournamentID   pgtype.UUID `json:"tournament_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Total match rows for a tournament. Generation requires this to be 0 (no
// fixtures exist) so it can never run twice or over a partial set.
func (q *Queries) CountMatchesForTournament(ctx context.Context, arg CountMatchesForTournamentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMatchesForTournament, arg.TournamentID, arg.OrganizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnfinishedGroupMatches = `-- name: CountUnfinishedGroupMatches :one
SELECT COUNT(*)
FROM   matches
WHERE  tournament_id   = $1
  AND  organization_id = $2
  AND  group_label IS NOT NULL
  AND  status NOT IN ('completed', 'walkover', 'cancelled')
`

type CountUnfinishedGroupMatchesParams struct {
	TournamentID   pgtype.UUID `json:"tournament_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Counts group-stage matches that have not yet reached a final result. Qualifier
// resolution requires this to be 0 (the whole group stage is decided). Cancelled
// group matches are treated as resolved (they yield no result either way).
func (q *Queries) CountUnfinishedGroupMatches(ctx context.Context, arg CountUnfinishedGroupMatchesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnfinishedGroupMatches, arg.TournamentID, arg.OrganizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertGeneratedMatch = `-- name: InsertGeneratedMatch :one
INSERT INTO matches (
    tournament_id,
    organization_id,
    round_number,
    round_name,
    match_number,
    home_team_id,
    away_team_id,
    home_player_id,
    away_player_id,
    status,
    group_label,
    next_match_id,
    next_match_slot,
    metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'scheduled', $10, $11, $12, $13)
RETURNING id, tournament_id, organization_id, round_number, round_name, match_number, home_team_id, away_team_id, home_player_id, away_player_id, venue, scheduled_at, started_at, ended_at, status, winner_team_id, winner_player_id, is_walkover, notes, metadata, created_at, updated_at, home_score, away_score, next_match_id, next_match_slot, group_label
`

type InsertGeneratedMatchParams struct {
	TournamentID   pgtype.UUID `json:"tournament_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	RoundNumber    *int16      `json:"round_number"`
	RoundName      *string     `json:"round_name"`
	MatchNumber    *int16      `json:"match_number"`
	HomeTeamID     pgtype.UUID `json:"home_team_id"`
	AwayTeamID     pgtype.UUID `json:"away_team_id"`
	HomePlayerID   pgtype.UUID `json:"home_player_id"`
	AwayPlayerID   pgtype.UUID `json:"away_player_id"`
	GroupLabel     *string     `json:"group_label"`
	NextMatchID    pgtype.UUID `json:"next_match_id"`
	NextMatchSlot  *int16      `json:"next_match_slot"`
	Metadata       []byte      `json:"metadata"`
}

// Inserts one generated match. Unlike CreateMatch this carries metadata (for
// group-qualifier slot mapping) and the bracket edge, and it does NOT check the
// tournament status — the generation service enforces registration_closed under
// the FOR UPDATE lock instead. Participants may be NULL (TBD/qualifier slots);
// the relaxed chk_matches_participants (FE-8B) permits partial/empty fills.
func (q *Queries) InsertGeneratedMatch(ctx context.Context, arg InsertGeneratedMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, insertGeneratedMatch,
		arg.TournamentID,
		arg.OrganizationID,
		arg.RoundNumber,
		arg.RoundName,
		arg.MatchNumber,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.HomePlayerID,
		arg.AwayPlayerID,
		arg.GroupLabel,
		arg.NextMatchID,
		arg.NextMatchSlot,
		arg.Metadata,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OrganizationID,
		&i.RoundNumber,
		&i.RoundName,
		&i.MatchNumber,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomePlayerID,
		&i.AwayPlayerID,
		&i.Venue,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.WinnerTeamID,
		&i.WinnerPlayerID,
		&i.IsWalkover,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HomeScore,
		&i.AwayScore,
		&i.NextMatchID,
		&i.NextMatchSlot,
		&i.GroupLabel,
	)
	return i, err
}

const listGroupMatchesForStandings = `-- name: ListGroupMatchesForStandings :many
SELECT group_label,
       home_team_id,
       away_team_id,
       home_player_id,
       away_player_id,
       winner_team_id,
       winner_player_id,
       is_walkover,
       home_score,
       away_score
FROM   matches
WHERE  tournament_id   = $1
  AND  organization_id = $2
  AND  group_label IS NOT NULL
  AND  status IN ('completed', 'walkover')
ORDER  BY group_label, created_at ASC
`

type ListGroupMatchesForStandingsParams struct {
	TournamentID   pgtype.UUID `json:"tournament_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListGroupMatchesForStandingsRow struct {
	GroupLabel     *string     `json:"group_label"`
	HomeTeamID     pgtype.UUID `json:"home_team_id"`
	AwayTeamID     pgtype.UUID `json:"away_team_id"`
	HomePlayerID   pgtype.UUID `json:"home_player_id"`
	AwayPlayerID   pgtype.UUID `json:"away_player_id"`
	WinnerTeamID   pgtype.UUID `json:"winner_team_id"`
	WinnerPlayerID pgtype.UUID `json:"winner_player_id"`
	IsWalkover     bool        `json:"is_walkover"`
	HomeScore      int32       `json:"home_score"`
	AwayScore      int32       `json:"away_score"`
}

// Returns concluded group-stage matches (per-group standings input). Mirrors the
// standings feed but scoped to grouped matches and carrying the group_label so
// the caller can partition by group.
func (q *Queries) ListGroupMatchesForStandings(ctx context.Context, arg ListGroupMatchesForStandingsParams) ([]ListGroupMatchesForStandingsRow, error) {
	rows, err := q.db.Query(ctx, listGroupMatchesForStandings, arg.TournamentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMatchesForStandingsRow{}
	for rows.Next() {
		var i ListGroupMatchesForStandingsRow
		if err := rows.Scan(
			&i.GroupLabel,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomePlayerID,
			&i.AwayPlayerID,
			&i.WinnerTeamID,
			&i.WinnerPlayerID,
			&i.IsWalkover,
			&i.HomeScore,
			&i.AwayScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnockoutQualifierMatches = `-- name: ListKnockoutQualifierMatches :many
SELECT id, round_number, home_team_id, away_team_id, home_player_id, away_player_id, metadata
FROM   matches
WHERE  tournament_id   = $1
  AND  organization_id = $2
  AND  group_label IS NULL
  AND  metadata ? 'qualifiers'
ORDER  BY round_number, match_number
`

type ListKnockoutQualifierMatchesParams struct {
	TournamentID   pgtype.UUID `json:"tournament_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListKnockoutQualifierMatchesRow struct {
	ID           pgtype.UUID `json:"id"`
	RoundNumber  *int16      `json:"round_number"`
	HomeTeamID   pgtype.UUID `json:"home_team_id"`
	AwayTeamID   pgtype.UUID `json:"away_team_id"`
	HomePlayerID pgtype.UUID `json:"home_player_id"`
	AwayPlayerID pgtype.UUID `json:"away_player_id"`
	Metadata     []byte      `json:"metadata"`
}

// Returns the knockout matches that still carry unresolved qualifier slots
// (metadata holds the group/rank mapping). Used by resolve-qualifiers to fill
// round-one knockout slots from the computed group standings.
func (q *Queries) ListKnockoutQualifierMatches(ctx context.Context, arg ListKnockoutQualifierMatchesParams) ([]ListKnockoutQualifierMatchesRow, error) {
	rows, err := q.db.Query(ctx, listKnockoutQualifierMatches, arg.TournamentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKnockoutQualifierMatchesRow{}
	for rows.Next() {
		var i ListKnockoutQualifierMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoundNumber,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomePlayerID,
			&i.AwayPlayerID,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTournamentForGeneration = `-- name: LockTournamentForGeneration :one

SELECT id, status, format, participant_type, settings
FROM   tournaments
WHERE  id              = $1
  AND  organization_id = $2
FOR    UPDATE
`

type LockTournamentForGenerationParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type LockTournamentForGenerationRow struct {
	ID              pgtype.UUID      `json:"id"`
	Status          TournamentStatus `json:"status"`
	Format          TournamentFormat `json:"format"`
	ParticipantType ParticipantType  `json:"participant_type"`
	Settings        []byte           `json:"settings"`
}

// Fixture generation queries (FE-8C).
// organization_id is always required to enforce tenant isolation.
// Locks the tournament row FOR UPDATE for the duration of a generation /
// resolve-qualifiers transaction, returning the fields the generator needs:
// status (the registration_closed / ongoing guard), format, participant_type
// (team vs individual column routing), and settings (for explainability merge).
func (q *Queries) LockTournamentForGeneration(ctx context.Context, arg LockTournamentForGenerationParams) (LockTournamentForGenerationRow, error) {
	row := q.db.QueryRow(ctx, lockTournamentForGeneration, arg.ID, arg.OrganizationID)
	var i LockTournamentForGenerationRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Format,
		&i.ParticipantType,
		&i.Settings,
	)
	return i, err
}

const updateTournamentSettings = `-- name: UpdateTournamentSettings :exec
UPDATE tournaments
SET    settings   = $3,
       updated_at = NOW()
WHERE  id              = $1
  AND  organization_id = $2
`

type UpdateTournamentSettingsParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Settings       []byte      `json:"settings"`
}

// Persists the merged settings JSONB (including the generation audit object).
func (q *Queries) UpdateTournamentSettings(ctx context.Context, arg UpdateTournamentSettingsParams) error {
	_, err := q.db.Exec(ctx, updateTournamentSettings, arg.ID, arg.OrganizationID, arg.Settings)
	return err
}
