// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelMatch = `-- name: CancelMatch :one
UPDATE matches
SET    status     = 'cancelled',
       updated_at = NOW()
WHERE  id              = $1
  AND  organization_id = $2
  AND  status          = $3
RETURNING id, tournament_id, organization_id, round_number, round_name, match_number, home_team_id, away_team_id, home_player_id, away_player_id, venue, scheduled_at, started_at, ended_at, status, winner_team_id, winner_player_id, is_walkover, notes, metadata, created_at, updated_at, home_score, away_score, next_match_id, next_match_slot, group_label
`

type CancelMatchParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Status         MatchStatus `json:"status"`
}

// Soft-cancel: sets status to 'cancelled'. Records are never hard-deleted so
// that future match_events and audit_log references remain resolvable.
// CAS guard: AND status = $3 (previous_status) ensures a concurrent transition
// that already moved the match to a terminal state causes this UPDATE to match
// 0 rows, returning ErrNoRows → ErrMatchNotUpdatable in the repository.
func (q *Queries) CancelMatch(ctx context.Context, arg CancelMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, cancelMatch, arg.ID, arg.OrganizationID, arg.Status)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OrganizationID,
		&i.RoundNumber,
		&i.RoundName,
		&i.MatchNumber,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomePlayerID,
		&i.AwayPlayerID,
		&i.Venue,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.WinnerTeamID,
		&i.WinnerPlayerID,
		&i.IsWalkover,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HomeScore,
		&i.AwayScore,
		&i.NextMatchID,
		&i.NextMatchSlot,
		&i.GroupLabel,
	)
	return i, err
}

const countMatches = `-- name: CountMatches :one
SELECT COUNT(*)
FROM   matches
WHERE  organization_id = $1
  AND  ($2::uuid IS NULL
        OR tournament_id = $2::uuid)
  AND  ($3::text IS NULL
        OR status::text = $3)
  AND  ($4::text IS NULL
        OR venue      ILIKE '%' || $4 || '%'
        OR round_name ILIKE '%' || $4 || '%')
`

type CountMatchesParams struct {
	OrganizationID     pgtype.UUID `json:"organization_id"`
	TournamentIDFilter pgtype.UUID `json:"tournament_id_filter"`
	StatusFilter       *string     `json:"status_filter"`
	SearchQuery        *string     `json:"search_query"`
}

// Returns the total count matching the same filters as ListMatchesPaginated.
// Used to build pagination metadata without fetching rows.
func (q *Queries) CountMatches(ctx context.Context, arg CountMatchesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMatches,
		arg.OrganizationID,
		arg.TournamentIDFilter,
		arg.StatusFilter,
		arg.SearchQuery,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMatchesFeedingSlot = `-- name: CountMatchesFeedingSlot :one
SELECT COUNT(*)
FROM   matches
WHERE  next_match_id    = $1
  AND  next_match_slot  = $2
  AND  organization_id  = $3
  -- $4 is the match being linked, excluded so a re-link of the SAME match is not
  -- self-flagged. NULL on create (no row yet); the OR keeps every row counted.
  AND  ($4::uuid IS NULL OR id <> $4::uuid)
  AND  status          <> 'cancelled'
`

type CountMatchesFeedingSlotParams struct {
	NextMatchID    pgtype.UUID `json:"next_match_id"`
	NextMatchSlot  *int16      `json:"next_match_slot"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Column4        pgtype.UUID `json:"column_4"`
}

// Counts active feeders already linked to a specific (successor, slot), excluding
// the match itself. Used to reject linking two feeders into the same slot, which
// would let the second silently overwrite the first's propagated winner.
// Cancelled feeders are excluded — they no longer advance anyone.
func (q *Queries) CountMatchesFeedingSlot(ctx context.Context, arg CountMatchesFeedingSlotParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMatchesFeedingSlot,
		arg.NextMatchID,
		arg.NextMatchSlot,
		arg.OrganizationID,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (
    tournament_id,
    organization_id,
    round_number,
    round_name,
    match_number,
    home_team_id,
    away_team_id,
    home_player_id,
    away_player_id,
    venue,
    scheduled_at,
    status,
    notes,
    next_match_id,
    next_match_slot,
    group_label
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, tournament_id, organization_id, round_number, round_name, match_number, home_team_id, away_team_id, home_player_id, away_player_id, venue, scheduled_at, started_at, ended_at, status, winner_team_id, winner_player_id, is_walkover, notes, metadata, created_at, updated_at, home_score, away_score, next_match_id, next_match_slot, group_label
`

type CreateMatchParams struct {
	TournamentID   pgtype.UUID        `json:"tournament_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	RoundNumber    *int16             `json:"round_number"`
	RoundName      *string            `json:"round_name"`
	MatchNumber    *int16             `json:"match_number"`
	HomeTeamID     pgtype.UUID        `json:"home_team_id"`
	AwayTeamID     pgtype.UUID        `json:"away_team_id"`
	HomePlayerID   pgtype.UUID        `json:"home_player_id"`
	AwayPlayerID   pgtype.UUID        `json:"away_player_id"`
	Venue          *string            `json:"venue"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	Status         MatchStatus        `json:"status"`
	Notes          *string            `json:"notes"`
	NextMatchID    pgtype.UUID        `json:"next_match_id"`
	NextMatchSlot  *int16             `json:"next_match_slot"`
	GroupLabel     *string            `json:"group_label"`
}

// Inserts a new scheduled match fixture. organization_id must equal the parent
// tournament's organization_id; this is enforced by trg_matches_org_consistency.
// status is always 'scheduled' on creation; is_walkover always FALSE.
// metadata defaults to '{}' via the table default.
func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, createMatch,
		arg.TournamentID,
		arg.OrganizationID,
		arg.RoundNumber,
		arg.RoundName,
		arg.MatchNumber,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.HomePlayerID,
		arg.AwayPlayerID,
		arg.Venue,
		arg.ScheduledAt,
		arg.Status,
		arg.Notes,
		arg.NextMatchID,
		arg.NextMatchSlot,
		arg.GroupLabel,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OrganizationID,
		&i.RoundNumber,
		&i.RoundName,
		&i.MatchNumber,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomePlayerID,
		&i.AwayPlayerID,
		&i.Venue,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.WinnerTeamID,
		&i.WinnerPlayerID,
		&i.IsWalkover,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HomeScore,
		&i.AwayScore,
		&i.NextMatchID,
		&i.NextMatchSlot,
		&i.GroupLabel,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one

SELECT id, tournament_id, organization_id, round_number, round_name, match_number, home_team_id, away_team_id, home_player_id, away_player_id, venue, scheduled_at, started_at, ended_at, status, winner_team_id, winner_player_id, is_walkover, notes, metadata, created_at, updated_at, home_score, away_score, next_match_id, next_match_slot, group_label
FROM   matches
WHERE  id              = $1
  AND  organization_id = $2
LIMIT  1
`

type GetMatchByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Matches queries
// organization_id is always required to enforce tenant isolation.
func (q *Queries) GetMatchByID(ctx context.Context, arg GetMatchByIDParams) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByID, arg.ID, arg.OrganizationID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OrganizationID,
		&i.RoundNumber,
		&i.RoundName,
		&i.MatchNumber,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomePlayerID,
		&i.AwayPlayerID,
		&i.Venue,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.WinnerTeamID,
		&i.WinnerPlayerID,
		&i.IsWalkover,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HomeScore,
		&i.AwayScore,
		&i.NextMatchID,
		&i.NextMatchSlot,
		&i.GroupLabel,
	)
	return i, err
}

const listCompletedMatchesByTournament = `-- name: ListCompletedMatchesByTournament :many
SELECT id,
       home_team_id,
       away_team_id,
       home_player_id,
       away_player_id,
       winner_team_id,
       winner_player_id,
       is_walkover,
       home_score,
       away_score
FROM   matches
WHERE  tournament_id   = $1
  AND  organization_id = $2
  AND  status          IN ('completed', 'walkover')
ORDER  BY created_at ASC
`

type ListCompletedMatchesByTournamentParams struct {
	TournamentID   pgtype.UUID `json:"tournament_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListCompletedMatchesByTournamentRow struct {
	ID             pgtype.UUID `json:"id"`
	HomeTeamID     pgtype.UUID `json:"home_team_id"`
	AwayTeamID     pgtype.UUID `json:"away_team_id"`
	HomePlayerID   pgtype.UUID `json:"home_player_id"`
	AwayPlayerID   pgtype.UUID `json:"away_player_id"`
	WinnerTeamID   pgtype.UUID `json:"winner_team_id"`
	WinnerPlayerID pgtype.UUID `json:"winner_player_id"`
	IsWalkover     bool        `json:"is_walkover"`
	HomeScore      int32       `json:"home_score"`
	AwayScore      int32       `json:"away_score"`
}

// Returns all matches with a final result for a tournament, in creation order.
// This means status IN ('completed','walkover'): a walkover is a terminal match
// with a 0-0 forfeit result and is_walkover=TRUE, so it MUST feed standings just
// like a scored completion. Omitting walkovers here silently drops forfeit
// results from the table (FE-8A standings-corruption bug).
// Used exclusively by the standings engine — standing computation MUST NOT
// read match_events; it reads only these pre-snapshotted score columns.
// Both organization_id and tournament_id are required to enforce multi-tenant
// isolation: a caller can only read matches belonging to their own tournament.
func (q *Queries) ListCompletedMatchesByTournament(ctx context.Context, arg ListCompletedMatchesByTournamentParams) ([]ListCompletedMatchesByTournamentRow, error) {
	rows, err := q.db.Query(ctx, listCompletedMatchesByTournament, arg.TournamentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompletedMatchesByTournamentRow{}
	for rows.Next() {
		var i ListCompletedMatchesByTournamentRow
		if err := rows.Scan(
			&i.ID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomePlayerID,
			&i.AwayPlayerID,
			&i.WinnerTeamID,
			&i.WinnerPlayerID,
			&i.IsWalkover,
			&i.HomeScore,
			&i.AwayScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesByTournament = `-- name: ListMatchesByTournament :many
SELECT id, tournament_id, organization_id, round_number, round_name, match_number, home_team_id, away_team_id, home_player_id, away_player_id, venue, scheduled_at, started_at, ended_at, status, winner_team_id, winner_player_id, is_walkover, notes, metadata, created_at, updated_at, home_score, away_score, next_match_id, next_match_slot, group_label
FROM   matches
WHERE  tournament_id   = $1
  AND  organization_id = $2
ORDER  BY round_number ASC NULLS LAST,
          match_number  ASC NULLS LAST
`

type ListMatchesByTournamentParams struct {
	TournamentID   pgtype.UUID `json:"tournament_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ListMatchesByTournament(ctx context.Context, arg ListMatchesByTournamentParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesByTournament, arg.TournamentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.OrganizationID,
			&i.RoundNumber,
			&i.RoundName,
			&i.MatchNumber,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomePlayerID,
			&i.AwayPlayerID,
			&i.Venue,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.WinnerTeamID,
			&i.WinnerPlayerID,
			&i.IsWalkover,
			&i.Notes,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeScore,
			&i.AwayScore,
			&i.NextMatchID,
			&i.NextMatchSlot,
			&i.GroupLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesPaginated = `-- name: ListMatchesPaginated :many
SELECT id, tournament_id, organization_id, round_number, round_name, match_number, home_team_id, away_team_id, home_player_id, away_player_id, venue, scheduled_at, started_at, ended_at, status, winner_team_id, winner_player_id, is_walkover, notes, metadata, created_at, updated_at, home_score, away_score, next_match_id, next_match_slot, group_label
FROM   matches
WHERE  organization_id = $1
  AND  ($2::uuid IS NULL
        OR tournament_id = $2::uuid)
  AND  ($3::text IS NULL
        OR status::text = $3)
  AND  ($4::text IS NULL
        OR venue      ILIKE '%' || $4 || '%'
        OR round_name ILIKE '%' || $4 || '%')
ORDER  BY scheduled_at ASC NULLS LAST,
          created_at   DESC
LIMIT  $6
OFFSET $5
`

type ListMatchesPaginatedParams struct {
	OrganizationID     pgtype.UUID `json:"organization_id"`
	TournamentIDFilter pgtype.UUID `json:"tournament_id_filter"`
	StatusFilter       *string     `json:"status_filter"`
	SearchQuery        *string     `json:"search_query"`
	PageOffset         int32       `json:"page_offset"`
	PageLimit          int32       `json:"page_limit"`
}

// Paginated listing of matches for an org.
// Optional tournament_id, status, and text search (venue / round_name) filters.
func (q *Queries) ListMatchesPaginated(ctx context.Context, arg ListMatchesPaginatedParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesPaginated,
		arg.OrganizationID,
		arg.TournamentIDFilter,
		arg.StatusFilter,
		arg.SearchQuery,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.OrganizationID,
			&i.RoundNumber,
			&i.RoundName,
			&i.MatchNumber,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomePlayerID,
			&i.AwayPlayerID,
			&i.Venue,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.WinnerTeamID,
			&i.WinnerPlayerID,
			&i.IsWalkover,
			&i.Notes,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HomeScore,
			&i.AwayScore,
			&i.NextMatchID,
			&i.NextMatchSlot,
			&i.GroupLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMatchForProgression = `-- name: LockMatchForProgression :one
SELECT id,
       organization_id,
       tournament_id,
       status,
       home_team_id,
       away_team_id,
       home_player_id,
       away_player_id
FROM   matches
WHERE  id              = $1
  AND  organization_id = $2
FOR    UPDATE
`

type LockMatchForProgressionParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type LockMatchForProgressionRow struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	TournamentID   pgtype.UUID `json:"tournament_id"`
	Status         MatchStatus `json:"status"`
	HomeTeamID     pgtype.UUID `json:"home_team_id"`
	AwayTeamID     pgtype.UUID `json:"away_team_id"`
	HomePlayerID   pgtype.UUID `json:"home_player_id"`
	AwayPlayerID   pgtype.UUID `json:"away_player_id"`
}

// Acquires an exclusive row-level lock on a downstream (successor) match while a
// feeder is being completed/walked-over, returning the fields propagation needs:
// status (the I3 downstream-state guard), tournament_id (the I5 same-tournament
// integrity check), and the four participant slots (so the writer preserves the
// slot it is NOT filling). FOR UPDATE serialises two feeders advancing into the
// same successor so each writes its own slot without a lost update.
func (q *Queries) LockMatchForProgression(ctx context.Context, arg LockMatchForProgressionParams) (LockMatchForProgressionRow, error) {
	row := q.db.QueryRow(ctx, lockMatchForProgression, arg.ID, arg.OrganizationID)
	var i LockMatchForProgressionRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TournamentID,
		&i.Status,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomePlayerID,
		&i.AwayPlayerID,
	)
	return i, err
}

const lockTournamentForShare = `-- name: LockTournamentForShare :one
SELECT status
FROM   tournaments
WHERE  id              = $1
  AND  organization_id = $2
FOR    SHARE
`

type LockTournamentForShareParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Acquires a row-level share lock on the tournament row inside a transaction.
// Used during match create/update to prevent a concurrent tournament cancellation
// from racing with a status-sensitive match operation.
// FOR SHARE: blocks concurrent UPDATEs (cancellation) while allowing other
// readers; does not block concurrent match creates for the same tournament.
func (q *Queries) LockTournamentForShare(ctx context.Context, arg LockTournamentForShareParams) (TournamentStatus, error) {
	row := q.db.QueryRow(ctx, lockTournamentForShare, arg.ID, arg.OrganizationID)
	var status TournamentStatus
	err := row.Scan(&status)
	return status, err
}

const setMatchParticipants = `-- name: SetMatchParticipants :execrows
UPDATE matches
SET    home_team_id     = $3,
       away_team_id     = $4,
       home_player_id   = $5,
       away_player_id   = $6,
       updated_at       = NOW()
WHERE  id              = $1
  AND  organization_id = $2
  AND  status          = 'scheduled'
`

type SetMatchParticipantsParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	HomeTeamID     pgtype.UUID `json:"home_team_id"`
	AwayTeamID     pgtype.UUID `json:"away_team_id"`
	HomePlayerID   pgtype.UUID `json:"home_player_id"`
	AwayPlayerID   pgtype.UUID `json:"away_player_id"`
}

// Writes the four participant slots of a (scheduled) successor match during
// winner propagation. Called only after LockMatchForProgression has locked the
// row and the service has verified status='scheduled'. The redundant
// status='scheduled' guard here is belt-and-suspenders against any future caller
// and yields rows-affected = 0 if the row left 'scheduled' under us.
func (q *Queries) SetMatchParticipants(ctx context.Context, arg SetMatchParticipantsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMatchParticipants,
		arg.ID,
		arg.OrganizationID,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.HomePlayerID,
		arg.AwayPlayerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setMatchWalkover = `-- name: SetMatchWalkover :one
UPDATE matches
SET    status           = 'walkover',
       is_walkover      = TRUE,
       winner_team_id   = $3,
       winner_player_id = $4,
       home_score       = 0,
       away_score       = 0,
       ended_at         = GREATEST(NOW(), started_at + INTERVAL '1 millisecond'),
       notes            = $5,
       updated_at       = NOW()
WHERE  id              = $1
  AND  organization_id = $2
  AND  status          = $6
RETURNING id, tournament_id, organization_id, round_number, round_name, match_number, home_team_id, away_team_id, home_player_id, away_player_id, venue, scheduled_at, started_at, ended_at, status, winner_team_id, winner_player_id, is_walkover, notes, metadata, created_at, updated_at, home_score, away_score, next_match_id, next_match_slot, group_label
`

type SetMatchWalkoverParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	WinnerTeamID   pgtype.UUID `json:"winner_team_id"`
	WinnerPlayerID pgtype.UUID `json:"winner_player_id"`
	Notes          *string     `json:"notes"`
	Status         MatchStatus `json:"status"`
}

// Awards a walkover: a terminal match with a result but no event log.
// Sets status='walkover', is_walkover=TRUE, the winner, and a 0-0 forfeit score.
// The winner ($3/$4) is resolved by the service to one of the match participants,
// satisfying chk_matches_winner_is_team/player_participant and
// chk_matches_walkover_has_winner. ended_at is stamped now, guarded by
// GREATEST(..., started_at + 1ms) so a live → walkover never violates
// chk_matches_ended_after_started; when started_at is NULL (scheduled → walkover)
// GREATEST ignores the NULL and returns NOW().
// CAS guard: AND status = $6 (previous_status) ensures a concurrent transition
// that already moved the match to a terminal state causes this UPDATE to match
// 0 rows, returning ErrNoRows → ErrMatchNotUpdatable in the repository.
func (q *Queries) SetMatchWalkover(ctx context.Context, arg SetMatchWalkoverParams) (Match, error) {
	row := q.db.QueryRow(ctx, setMatchWalkover,
		arg.ID,
		arg.OrganizationID,
		arg.WinnerTeamID,
		arg.WinnerPlayerID,
		arg.Notes,
		arg.Status,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OrganizationID,
		&i.RoundNumber,
		&i.RoundName,
		&i.MatchNumber,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomePlayerID,
		&i.AwayPlayerID,
		&i.Venue,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.WinnerTeamID,
		&i.WinnerPlayerID,
		&i.IsWalkover,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HomeScore,
		&i.AwayScore,
		&i.NextMatchID,
		&i.NextMatchSlot,
		&i.GroupLabel,
	)
	return i, err
}

const updateMatch = `-- name: UpdateMatch :one
UPDATE matches
SET    round_number     = $3,
       round_name       = $4,
       match_number     = $5,
       home_team_id     = $6,
       away_team_id     = $7,
       home_player_id   = $8,
       away_player_id   = $9,
       venue            = $10,
       scheduled_at     = $11,
       started_at       = $12,
       ended_at         = CASE WHEN $13::TIMESTAMPTZ IS NOT NULL THEN GREATEST($13::TIMESTAMPTZ, started_at + INTERVAL '1 millisecond') ELSE NULL END,
       status           = $14,
       winner_team_id   = $15,
       winner_player_id = $16,
       notes            = $17,
       home_score       = $18,
       away_score       = $19,
       next_match_id    = $20,
       next_match_slot  = $21,
       group_label      = $22,
       updated_at       = NOW()
WHERE  id              = $1
  AND  organization_id = $2
  AND  status          = $23
RETURNING id, tournament_id, organization_id, round_number, round_name, match_number, home_team_id, away_team_id, home_player_id, away_player_id, venue, scheduled_at, started_at, ended_at, status, winner_team_id, winner_player_id, is_walkover, notes, metadata, created_at, updated_at, home_score, away_score, next_match_id, next_match_slot, group_label
`

type UpdateMatchParams struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	RoundNumber    *int16             `json:"round_number"`
	RoundName      *string            `json:"round_name"`
	MatchNumber    *int16             `json:"match_number"`
	HomeTeamID     pgtype.UUID        `json:"home_team_id"`
	AwayTeamID     pgtype.UUID        `json:"away_team_id"`
	HomePlayerID   pgtype.UUID        `json:"home_player_id"`
	AwayPlayerID   pgtype.UUID        `json:"away_player_id"`
	Venue          *string            `json:"venue"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	Column13       pgtype.Timestamptz `json:"column_13"`
	Status         MatchStatus        `json:"status"`
	WinnerTeamID   pgtype.UUID        `json:"winner_team_id"`
	WinnerPlayerID pgtype.UUID        `json:"winner_player_id"`
	Notes          *string            `json:"notes"`
	HomeScore      int32              `json:"home_score"`
	AwayScore      int32              `json:"away_score"`
	NextMatchID    pgtype.UUID        `json:"next_match_id"`
	NextMatchSlot  *int16             `json:"next_match_slot"`
	GroupLabel     *string            `json:"group_label"`
	Status_2       MatchStatus        `json:"status_2"`
}

// Full mutable-field update with compare-and-swap (CAS) status guard.
// Service layer merges partial request fields over current state.
// id, organization_id, tournament_id, is_walkover, metadata, and created_at
// are immutable and never appear in the SET clause.
// started_at and ended_at are stamped by the service during lifecycle transitions.
// home_score and away_score ($18, $19) are 0 for all non-completion transitions;
// for the live → completed transition the repository fills them in after computing
// the final score from the effective event log under a FOR UPDATE lock on this row.
// CAS guard: AND status = $20 (previous_status from the service read) ensures
// that if a concurrent request already changed the status between the service
// read and this write, this UPDATE matches 0 rows and returns ErrNoRows, which
// the repository maps to ErrMatchNotUpdatable.
func (q *Queries) UpdateMatch(ctx context.Context, arg UpdateMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, updateMatch,
		arg.ID,
		arg.OrganizationID,
		arg.RoundNumber,
		arg.RoundName,
		arg.MatchNumber,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.HomePlayerID,
		arg.AwayPlayerID,
		arg.Venue,
		arg.ScheduledAt,
		arg.StartedAt,
		arg.Column13,
		arg.Status,
		arg.WinnerTeamID,
		arg.WinnerPlayerID,
		arg.Notes,
		arg.HomeScore,
		arg.AwayScore,
		arg.NextMatchID,
		arg.NextMatchSlot,
		arg.GroupLabel,
		arg.Status_2,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OrganizationID,
		&i.RoundNumber,
		&i.RoundName,
		&i.MatchNumber,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomePlayerID,
		&i.AwayPlayerID,
		&i.Venue,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.WinnerTeamID,
		&i.WinnerPlayerID,
		&i.IsWalkover,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HomeScore,
		&i.AwayScore,
		&i.NextMatchID,
		&i.NextMatchSlot,
		&i.GroupLabel,
	)
	return i, err
}
