// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMatchByID = `-- name: GetMatchByID :one

SELECT id, tournament_id, organization_id, round_number, round_name, match_number, home_team_id, away_team_id, home_player_id, away_player_id, venue, scheduled_at, started_at, ended_at, status, winner_team_id, winner_player_id, is_walkover, notes, metadata, created_at, updated_at
FROM   matches
WHERE  id              = $1
  AND  organization_id = $2
LIMIT  1
`

type GetMatchByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Matches queries
// organization_id is always required to enforce tenant isolation.
func (q *Queries) GetMatchByID(ctx context.Context, arg GetMatchByIDParams) (Match, error) {
	row := q.db.QueryRow(ctx, getMatchByID, arg.ID, arg.OrganizationID)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OrganizationID,
		&i.RoundNumber,
		&i.RoundName,
		&i.MatchNumber,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomePlayerID,
		&i.AwayPlayerID,
		&i.Venue,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Status,
		&i.WinnerTeamID,
		&i.WinnerPlayerID,
		&i.IsWalkover,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMatchesByTournament = `-- name: ListMatchesByTournament :many
SELECT id, tournament_id, organization_id, round_number, round_name, match_number, home_team_id, away_team_id, home_player_id, away_player_id, venue, scheduled_at, started_at, ended_at, status, winner_team_id, winner_player_id, is_walkover, notes, metadata, created_at, updated_at
FROM   matches
WHERE  tournament_id   = $1
  AND  organization_id = $2
ORDER  BY round_number ASC NULLS LAST,
          match_number  ASC NULLS LAST
`

type ListMatchesByTournamentParams struct {
	TournamentID   pgtype.UUID `json:"tournament_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) ListMatchesByTournament(ctx context.Context, arg ListMatchesByTournamentParams) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesByTournament, arg.TournamentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Match{}
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.OrganizationID,
			&i.RoundNumber,
			&i.RoundName,
			&i.MatchNumber,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomePlayerID,
			&i.AwayPlayerID,
			&i.Venue,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Status,
			&i.WinnerTeamID,
			&i.WinnerPlayerID,
			&i.IsWalkover,
			&i.Notes,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
