// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: match_events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEffectiveMatchEventsByMatch = `-- name: CountEffectiveMatchEventsByMatch :one
SELECT COUNT(*)
FROM   match_events me
WHERE  me.match_id        = $1
  AND  me.organization_id = $2
  AND  me.id NOT IN (
           SELECT c.cancels_event_id
           FROM   match_events c
           WHERE  c.match_id         = $1
             AND  c.cancels_event_id IS NOT NULL
       )
`

type CountEffectiveMatchEventsByMatchParams struct {
	MatchID        pgtype.UUID `json:"match_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Effective event count (excludes cancelled) for pagination metadata.
func (q *Queries) CountEffectiveMatchEventsByMatch(ctx context.Context, arg CountEffectiveMatchEventsByMatchParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEffectiveMatchEventsByMatch, arg.MatchID, arg.OrganizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMatchEventsByMatch = `-- name: CountMatchEventsByMatch :one
SELECT COUNT(*)
FROM   match_events
WHERE  match_id        = $1
  AND  organization_id = $2
`

type CountMatchEventsByMatchParams struct {
	MatchID        pgtype.UUID `json:"match_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Total event count (raw) for pagination metadata.
func (q *Queries) CountMatchEventsByMatch(ctx context.Context, arg CountMatchEventsByMatchParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMatchEventsByMatch, arg.MatchID, arg.OrganizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMatchEventsByType = `-- name: CountMatchEventsByType :one
SELECT COUNT(*)
FROM   match_events
WHERE  match_id   = $1
  AND  event_type = $2
`

type CountMatchEventsByTypeParams struct {
	MatchID   pgtype.UUID    `json:"match_id"`
	EventType MatchEventType `json:"event_type"`
}

// Returns the number of events of a specific type for a match. Used inside the
// FOR UPDATE transaction to enforce lifecycle event uniqueness (only one
// match_started and one match_ended allowed per match).
func (q *Queries) CountMatchEventsByType(ctx context.Context, arg CountMatchEventsByTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMatchEventsByType, arg.MatchID, arg.EventType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMatchEvent = `-- name: CreateMatchEvent :one
INSERT INTO match_events (
    match_id,
    organization_id,
    sequence_number,
    event_type,
    team_id,
    player_id,
    period,
    clock_seconds,
    payload,
    recorded_by,
    recorded_at,
    cancels_event_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, match_id, organization_id, sequence_number, event_type, team_id, player_id, period, clock_seconds, payload, recorded_by, recorded_at, cancels_event_id, created_at
`

type CreateMatchEventParams struct {
	MatchID        pgtype.UUID        `json:"match_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	SequenceNumber int64              `json:"sequence_number"`
	EventType      MatchEventType     `json:"event_type"`
	TeamID         pgtype.UUID        `json:"team_id"`
	PlayerID       pgtype.UUID        `json:"player_id"`
	Period         *int16             `json:"period"`
	ClockSeconds   *int32             `json:"clock_seconds"`
	Payload        []byte             `json:"payload"`
	RecordedBy     pgtype.UUID        `json:"recorded_by"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
	CancelsEventID pgtype.UUID        `json:"cancels_event_id"`
}

func (q *Queries) CreateMatchEvent(ctx context.Context, arg CreateMatchEventParams) (MatchEvent, error) {
	row := q.db.QueryRow(ctx, createMatchEvent,
		arg.MatchID,
		arg.OrganizationID,
		arg.SequenceNumber,
		arg.EventType,
		arg.TeamID,
		arg.PlayerID,
		arg.Period,
		arg.ClockSeconds,
		arg.Payload,
		arg.RecordedBy,
		arg.RecordedAt,
		arg.CancelsEventID,
	)
	var i MatchEvent
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.OrganizationID,
		&i.SequenceNumber,
		&i.EventType,
		&i.TeamID,
		&i.PlayerID,
		&i.Period,
		&i.ClockSeconds,
		&i.Payload,
		&i.RecordedBy,
		&i.RecordedAt,
		&i.CancelsEventID,
		&i.CreatedAt,
	)
	return i, err
}

const getEventCancellation = `-- name: GetEventCancellation :one
SELECT id
FROM   match_events
WHERE  match_id         = $1
  AND  cancels_event_id = $2
LIMIT  1
`

type GetEventCancellationParams struct {
	MatchID        pgtype.UUID `json:"match_id"`
	CancelsEventID pgtype.UUID `json:"cancels_event_id"`
}

// Returns the id of the score_correction event that has already cancelled the
// specified target event. If found, the target is already cancelled and a
// second cancellation must be rejected. ErrNoRows means the target is not yet
// cancelled and the correction may proceed.
func (q *Queries) GetEventCancellation(ctx context.Context, arg GetEventCancellationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getEventCancellation, arg.MatchID, arg.CancelsEventID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getMatchEventByID = `-- name: GetMatchEventByID :one
SELECT id, match_id, organization_id, sequence_number, event_type, team_id, player_id, period, clock_seconds, payload, recorded_by, recorded_at, cancels_event_id, created_at
FROM   match_events
WHERE  id              = $1
  AND  organization_id = $2
LIMIT  1
`

type GetMatchEventByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Fetches a single event scoped to its organization. Org-scoping prevents
// reading events across tenant boundaries.
func (q *Queries) GetMatchEventByID(ctx context.Context, arg GetMatchEventByIDParams) (MatchEvent, error) {
	row := q.db.QueryRow(ctx, getMatchEventByID, arg.ID, arg.OrganizationID)
	var i MatchEvent
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.OrganizationID,
		&i.SequenceNumber,
		&i.EventType,
		&i.TeamID,
		&i.PlayerID,
		&i.Period,
		&i.ClockSeconds,
		&i.Payload,
		&i.RecordedBy,
		&i.RecordedAt,
		&i.CancelsEventID,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchEventByMatchAndID = `-- name: GetMatchEventByMatchAndID :one
SELECT id, match_id, organization_id, sequence_number, event_type, team_id, player_id, period, clock_seconds, payload, recorded_by, recorded_at, cancels_event_id, created_at
FROM   match_events
WHERE  id              = $1
  AND  match_id        = $2
  AND  organization_id = $3
LIMIT  1
`

type GetMatchEventByMatchAndIDParams struct {
	ID             pgtype.UUID `json:"id"`
	MatchID        pgtype.UUID `json:"match_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Fetches a single event scoped to its match AND organization.
// Enforces the URL resource hierarchy: the event must belong to the match
// specified in the URL, not just to the organization. Returns ErrNoRows
// (mapped to ErrEventNotFound) when the event exists in the org but belongs
// to a different match — preventing cross-match event retrieval.
func (q *Queries) GetMatchEventByMatchAndID(ctx context.Context, arg GetMatchEventByMatchAndIDParams) (MatchEvent, error) {
	row := q.db.QueryRow(ctx, getMatchEventByMatchAndID, arg.ID, arg.MatchID, arg.OrganizationID)
	var i MatchEvent
	err := row.Scan(
		&i.ID,
		&i.MatchID,
		&i.OrganizationID,
		&i.SequenceNumber,
		&i.EventType,
		&i.TeamID,
		&i.PlayerID,
		&i.Period,
		&i.ClockSeconds,
		&i.Payload,
		&i.RecordedBy,
		&i.RecordedAt,
		&i.CancelsEventID,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchEventForCorrection = `-- name: GetMatchEventForCorrection :one
SELECT id, match_id, event_type
FROM   match_events
WHERE  id = $1
LIMIT  1
`

type GetMatchEventForCorrectionRow struct {
	ID        pgtype.UUID    `json:"id"`
	MatchID   pgtype.UUID    `json:"match_id"`
	EventType MatchEventType `json:"event_type"`
}

// Fetches the minimal fields needed to validate a score_correction target:
// existence, same-match check, and type check (correction chains are forbidden).
// Does not scope by organization_id: cross-match detection provides the
// isolation boundary (no two matches share a UUID).
func (q *Queries) GetMatchEventForCorrection(ctx context.Context, id pgtype.UUID) (GetMatchEventForCorrectionRow, error) {
	row := q.db.QueryRow(ctx, getMatchEventForCorrection, id)
	var i GetMatchEventForCorrectionRow
	err := row.Scan(&i.ID, &i.MatchID, &i.EventType)
	return i, err
}

const getMaxSequenceNumber = `-- name: GetMaxSequenceNumber :one
SELECT COALESCE(MAX(sequence_number), 0)::bigint
FROM   match_events
WHERE  match_id = $1
`

// Returns the current maximum sequence_number for a match (0 when no events
// exist yet). Must be called inside the FOR UPDATE transaction so the lock on
// the parent match row prevents a concurrent insert from changing this value
// before the new INSERT executes.
func (q *Queries) GetMaxSequenceNumber(ctx context.Context, matchID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getMaxSequenceNumber, matchID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const isPlayerOnParticipatingTeam = `-- name: IsPlayerOnParticipatingTeam :one
SELECT EXISTS(
    SELECT 1
    FROM   team_memberships
    WHERE  player_id  = $1
      AND  (team_id   = $2
            OR team_id = $3)
      AND  status     = 'active'
) AS on_team
`

type IsPlayerOnParticipatingTeamParams struct {
	PlayerID   pgtype.UUID `json:"player_id"`
	HomeTeamID pgtype.UUID `json:"home_team_id"`
	AwayTeamID pgtype.UUID `json:"away_team_id"`
}

// Returns true if the player has an active team_membership on either the home
// or away team of a match. Used in team-format matches to validate that a
// player_id in an event belongs to one of the match participants.
func (q *Queries) IsPlayerOnParticipatingTeam(ctx context.Context, arg IsPlayerOnParticipatingTeamParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPlayerOnParticipatingTeam, arg.PlayerID, arg.HomeTeamID, arg.AwayTeamID)
	var on_team bool
	err := row.Scan(&on_team)
	return on_team, err
}

const isPlayerOnTeam = `-- name: IsPlayerOnTeam :one
SELECT EXISTS(
    SELECT 1
    FROM   team_memberships
    WHERE  player_id = $1
      AND  team_id   = $2
      AND  status    = 'active'
) AS on_team
`

type IsPlayerOnTeamParams struct {
	PlayerID pgtype.UUID `json:"player_id"`
	TeamID   pgtype.UUID `json:"team_id"`
}

// Returns true if the player has an active team_membership on the specified
// team. Used when both team_id and player_id are present in a single event to
// verify the player actually belongs to the stated team.
func (q *Queries) IsPlayerOnTeam(ctx context.Context, arg IsPlayerOnTeamParams) (bool, error) {
	row := q.db.QueryRow(ctx, isPlayerOnTeam, arg.PlayerID, arg.TeamID)
	var on_team bool
	err := row.Scan(&on_team)
	return on_team, err
}

const listEffectiveMatchEventsByMatch = `-- name: ListEffectiveMatchEventsByMatch :many
SELECT me.id, me.match_id, me.organization_id, me.sequence_number, me.event_type, me.team_id, me.player_id, me.period, me.clock_seconds, me.payload, me.recorded_by, me.recorded_at, me.cancels_event_id, me.created_at
FROM   match_events me
WHERE  me.match_id        = $1
  AND  me.organization_id = $2
  AND  me.id NOT IN (
           SELECT c.cancels_event_id
           FROM   match_events c
           WHERE  c.match_id         = $1
             AND  c.cancels_event_id IS NOT NULL
       )
ORDER  BY me.sequence_number ASC
LIMIT  $4
OFFSET $3
`

type ListEffectiveMatchEventsByMatchParams struct {
	MatchID        pgtype.UUID `json:"match_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	PageOffset     int32       `json:"page_offset"`
	PageLimit      int32       `json:"page_limit"`
}

// Effective event timeline: excludes events that have been cancelled by a
// score_correction. An event is cancelled when its id appears in any
// cancels_event_id within the same match. Use this view for score derivation
// and live display. The raw timeline (ListMatchEventsByMatch) is available for
// audit and correction history.
func (q *Queries) ListEffectiveMatchEventsByMatch(ctx context.Context, arg ListEffectiveMatchEventsByMatchParams) ([]MatchEvent, error) {
	rows, err := q.db.Query(ctx, listEffectiveMatchEventsByMatch,
		arg.MatchID,
		arg.OrganizationID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchEvent{}
	for rows.Next() {
		var i MatchEvent
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.OrganizationID,
			&i.SequenceNumber,
			&i.EventType,
			&i.TeamID,
			&i.PlayerID,
			&i.Period,
			&i.ClockSeconds,
			&i.Payload,
			&i.RecordedBy,
			&i.RecordedAt,
			&i.CancelsEventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchEventsByMatch = `-- name: ListMatchEventsByMatch :many
SELECT id, match_id, organization_id, sequence_number, event_type, team_id, player_id, period, clock_seconds, payload, recorded_by, recorded_at, cancels_event_id, created_at
FROM   match_events
WHERE  match_id        = $1
  AND  organization_id = $2
ORDER  BY sequence_number ASC
LIMIT  $4
OFFSET $3
`

type ListMatchEventsByMatchParams struct {
	MatchID        pgtype.UUID `json:"match_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	PageOffset     int32       `json:"page_offset"`
	PageLimit      int32       `json:"page_limit"`
}

// Raw event timeline in strict sequence order. Includes all events, even
// those cancelled by a score_correction. Used for audit trail and replay.
func (q *Queries) ListMatchEventsByMatch(ctx context.Context, arg ListMatchEventsByMatchParams) ([]MatchEvent, error) {
	rows, err := q.db.Query(ctx, listMatchEventsByMatch,
		arg.MatchID,
		arg.OrganizationID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchEvent{}
	for rows.Next() {
		var i MatchEvent
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.OrganizationID,
			&i.SequenceNumber,
			&i.EventType,
			&i.TeamID,
			&i.PlayerID,
			&i.Period,
			&i.ClockSeconds,
			&i.Payload,
			&i.RecordedBy,
			&i.RecordedAt,
			&i.CancelsEventID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockMatchForUpdate = `-- name: LockMatchForUpdate :one

SELECT id,
       organization_id,
       status,
       home_team_id,
       away_team_id,
       home_player_id,
       away_player_id
FROM   matches
WHERE  id              = $1
  AND  organization_id = $2
FOR    UPDATE
`

type LockMatchForUpdateParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type LockMatchForUpdateRow struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Status         MatchStatus `json:"status"`
	HomeTeamID     pgtype.UUID `json:"home_team_id"`
	AwayTeamID     pgtype.UUID `json:"away_team_id"`
	HomePlayerID   pgtype.UUID `json:"home_player_id"`
	AwayPlayerID   pgtype.UUID `json:"away_player_id"`
}

// Match Events queries
// organization_id is always required to enforce tenant isolation.
// This table is append-only: no UPDATE or DELETE queries are ever added.
// sequence_number is always computed server-side inside a FOR UPDATE transaction.
// Acquires an exclusive row-level lock on the match row for the duration of
// the event-insert transaction. The lock serialises all concurrent event inserts
// for the same match, making MAX(sequence_number)+1 and match-status validation
// race-free. Also returns participant fields needed for in-transaction validation.
func (q *Queries) LockMatchForUpdate(ctx context.Context, arg LockMatchForUpdateParams) (LockMatchForUpdateRow, error) {
	row := q.db.QueryRow(ctx, lockMatchForUpdate, arg.ID, arg.OrganizationID)
	var i LockMatchForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Status,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomePlayerID,
		&i.AwayPlayerID,
	)
	return i, err
}
