// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllMediaByOrg = `-- name: CountAllMediaByOrg :one
SELECT COUNT(*) FROM media_attachments
WHERE organization_id = $1
`

func (q *Queries) CountAllMediaByOrg(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAllMediaByOrg, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMediaAttachmentsByEntity = `-- name: CountMediaAttachmentsByEntity :one
SELECT COUNT(*) FROM media_attachments
WHERE organization_id = $1
  AND entity_type     = $2
  AND entity_id       = $3
`

type CountMediaAttachmentsByEntityParams struct {
	OrganizationID pgtype.UUID     `json:"organization_id"`
	EntityType     MediaEntityType `json:"entity_type"`
	EntityID       pgtype.UUID     `json:"entity_id"`
}

func (q *Queries) CountMediaAttachmentsByEntity(ctx context.Context, arg CountMediaAttachmentsByEntityParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMediaAttachmentsByEntity, arg.OrganizationID, arg.EntityType, arg.EntityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMediaAttachment = `-- name: CreateMediaAttachment :one


INSERT INTO media_attachments (
    organization_id,
    entity_type,
    entity_id,
    media_type,
    file_name,
    file_url,
    storage_key,
    content_hash,
    file_size,
    mime_type,
    width,
    height,
    alt_text,
    is_primary,
    sort_order,
    uploaded_by,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, organization_id, entity_type, entity_id, media_type, file_name, file_url, file_size, mime_type, width, height, duration_secs, alt_text, is_primary, sort_order, uploaded_by, metadata, created_at, updated_at, storage_key, content_hash
`

type CreateMediaAttachmentParams struct {
	OrganizationID pgtype.UUID     `json:"organization_id"`
	EntityType     MediaEntityType `json:"entity_type"`
	EntityID       pgtype.UUID     `json:"entity_id"`
	MediaType      MediaType       `json:"media_type"`
	FileName       string          `json:"file_name"`
	FileUrl        string          `json:"file_url"`
	StorageKey     string          `json:"storage_key"`
	ContentHash    string          `json:"content_hash"`
	FileSize       *int64          `json:"file_size"`
	MimeType       *string         `json:"mime_type"`
	Width          *int16          `json:"width"`
	Height         *int16          `json:"height"`
	AltText        *string         `json:"alt_text"`
	IsPrimary      bool            `json:"is_primary"`
	SortOrder      int16           `json:"sort_order"`
	UploadedBy     pgtype.UUID     `json:"uploaded_by"`
	Metadata       []byte          `json:"metadata"`
}

// =============================================================================
// Queries : media_attachments
// Module  : internal/media
// =============================================================================
// ─────────────────────────────────────────────────────────────────────────────
// WRITES
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) CreateMediaAttachment(ctx context.Context, arg CreateMediaAttachmentParams) (MediaAttachment, error) {
	row := q.db.QueryRow(ctx, createMediaAttachment,
		arg.OrganizationID,
		arg.EntityType,
		arg.EntityID,
		arg.MediaType,
		arg.FileName,
		arg.FileUrl,
		arg.StorageKey,
		arg.ContentHash,
		arg.FileSize,
		arg.MimeType,
		arg.Width,
		arg.Height,
		arg.AltText,
		arg.IsPrimary,
		arg.SortOrder,
		arg.UploadedBy,
		arg.Metadata,
	)
	var i MediaAttachment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EntityType,
		&i.EntityID,
		&i.MediaType,
		&i.FileName,
		&i.FileUrl,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationSecs,
		&i.AltText,
		&i.IsPrimary,
		&i.SortOrder,
		&i.UploadedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageKey,
		&i.ContentHash,
	)
	return i, err
}

const deleteMediaAttachment = `-- name: DeleteMediaAttachment :execrows
DELETE FROM media_attachments
WHERE id              = $1
  AND organization_id = $2
`

type DeleteMediaAttachmentParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteMediaAttachment(ctx context.Context, arg DeleteMediaAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMediaAttachment, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMediaAttachmentByContentHash = `-- name: GetMediaAttachmentByContentHash :one
SELECT id, organization_id, entity_type, entity_id, media_type, file_name, file_url, file_size, mime_type, width, height, duration_secs, alt_text, is_primary, sort_order, uploaded_by, metadata, created_at, updated_at, storage_key, content_hash FROM media_attachments
WHERE organization_id = $1
  AND entity_type     = $2
  AND entity_id       = $3
  AND content_hash    = $4
LIMIT 1
`

type GetMediaAttachmentByContentHashParams struct {
	OrganizationID pgtype.UUID     `json:"organization_id"`
	EntityType     MediaEntityType `json:"entity_type"`
	EntityID       pgtype.UUID     `json:"entity_id"`
	ContentHash    string          `json:"content_hash"`
}

// Duplicate detection: same entity + same content hash = existing record.
func (q *Queries) GetMediaAttachmentByContentHash(ctx context.Context, arg GetMediaAttachmentByContentHashParams) (MediaAttachment, error) {
	row := q.db.QueryRow(ctx, getMediaAttachmentByContentHash,
		arg.OrganizationID,
		arg.EntityType,
		arg.EntityID,
		arg.ContentHash,
	)
	var i MediaAttachment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EntityType,
		&i.EntityID,
		&i.MediaType,
		&i.FileName,
		&i.FileUrl,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationSecs,
		&i.AltText,
		&i.IsPrimary,
		&i.SortOrder,
		&i.UploadedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageKey,
		&i.ContentHash,
	)
	return i, err
}

const getMediaAttachmentByID = `-- name: GetMediaAttachmentByID :one

SELECT id, organization_id, entity_type, entity_id, media_type, file_name, file_url, file_size, mime_type, width, height, duration_secs, alt_text, is_primary, sort_order, uploaded_by, metadata, created_at, updated_at, storage_key, content_hash FROM media_attachments
WHERE id              = $1
  AND organization_id = $2
LIMIT 1
`

type GetMediaAttachmentByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// ─────────────────────────────────────────────────────────────────────────────
// READS
// ─────────────────────────────────────────────────────────────────────────────
// org-scoped lookup: prevents cross-tenant reads (BOLA protection).
func (q *Queries) GetMediaAttachmentByID(ctx context.Context, arg GetMediaAttachmentByIDParams) (MediaAttachment, error) {
	row := q.db.QueryRow(ctx, getMediaAttachmentByID, arg.ID, arg.OrganizationID)
	var i MediaAttachment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EntityType,
		&i.EntityID,
		&i.MediaType,
		&i.FileName,
		&i.FileUrl,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationSecs,
		&i.AltText,
		&i.IsPrimary,
		&i.SortOrder,
		&i.UploadedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageKey,
		&i.ContentHash,
	)
	return i, err
}

const listAllMediaByOrg = `-- name: ListAllMediaByOrg :many
SELECT id, organization_id, entity_type, entity_id, media_type, file_name, file_url, file_size, mime_type, width, height, duration_secs, alt_text, is_primary, sort_order, uploaded_by, metadata, created_at, updated_at, storage_key, content_hash FROM media_attachments
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT  $2
OFFSET $3
`

type ListAllMediaByOrgParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

// Org-wide listing (no entity filter). Used for the media management panel.
func (q *Queries) ListAllMediaByOrg(ctx context.Context, arg ListAllMediaByOrgParams) ([]MediaAttachment, error) {
	rows, err := q.db.Query(ctx, listAllMediaByOrg, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaAttachment{}
	for rows.Next() {
		var i MediaAttachment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EntityType,
			&i.EntityID,
			&i.MediaType,
			&i.FileName,
			&i.FileUrl,
			&i.FileSize,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.DurationSecs,
			&i.AltText,
			&i.IsPrimary,
			&i.SortOrder,
			&i.UploadedBy,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StorageKey,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaAttachmentsByEntity = `-- name: ListMediaAttachmentsByEntity :many
SELECT id, organization_id, entity_type, entity_id, media_type, file_name, file_url, file_size, mime_type, width, height, duration_secs, alt_text, is_primary, sort_order, uploaded_by, metadata, created_at, updated_at, storage_key, content_hash FROM media_attachments
WHERE organization_id = $1
  AND entity_type     = $2
  AND entity_id       = $3
ORDER BY is_primary DESC, sort_order ASC, created_at DESC
LIMIT  $4
OFFSET $5
`

type ListMediaAttachmentsByEntityParams struct {
	OrganizationID pgtype.UUID     `json:"organization_id"`
	EntityType     MediaEntityType `json:"entity_type"`
	EntityID       pgtype.UUID     `json:"entity_id"`
	Limit          int32           `json:"limit"`
	Offset         int32           `json:"offset"`
}

// Returns all attachments for a specific entity, primary first, then by sort
// order ascending, then newest first within the same sort_order.
func (q *Queries) ListMediaAttachmentsByEntity(ctx context.Context, arg ListMediaAttachmentsByEntityParams) ([]MediaAttachment, error) {
	rows, err := q.db.Query(ctx, listMediaAttachmentsByEntity,
		arg.OrganizationID,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MediaAttachment{}
	for rows.Next() {
		var i MediaAttachment
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EntityType,
			&i.EntityID,
			&i.MediaType,
			&i.FileName,
			&i.FileUrl,
			&i.FileSize,
			&i.MimeType,
			&i.Width,
			&i.Height,
			&i.DurationSecs,
			&i.AltText,
			&i.IsPrimary,
			&i.SortOrder,
			&i.UploadedBy,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StorageKey,
			&i.ContentHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPrimaryMediaAttachment = `-- name: LockPrimaryMediaAttachment :one
SELECT id, organization_id, entity_type, entity_id, media_type, file_name, file_url, file_size, mime_type, width, height, duration_secs, alt_text, is_primary, sort_order, uploaded_by, metadata, created_at, updated_at, storage_key, content_hash FROM media_attachments
WHERE organization_id = $1
  AND entity_type     = $2
  AND entity_id       = $3
  AND is_primary      = TRUE
LIMIT 1
FOR UPDATE
`

type LockPrimaryMediaAttachmentParams struct {
	OrganizationID pgtype.UUID     `json:"organization_id"`
	EntityType     MediaEntityType `json:"entity_type"`
	EntityID       pgtype.UUID     `json:"entity_id"`
}

// Acquires FOR UPDATE row lock on the current primary attachment for an entity.
// Used in the primary-swap transaction to serialise concurrent swap requests.
// Returns NULL (pgx.ErrNoRows) when no primary exists for the entity.
func (q *Queries) LockPrimaryMediaAttachment(ctx context.Context, arg LockPrimaryMediaAttachmentParams) (MediaAttachment, error) {
	row := q.db.QueryRow(ctx, lockPrimaryMediaAttachment, arg.OrganizationID, arg.EntityType, arg.EntityID)
	var i MediaAttachment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EntityType,
		&i.EntityID,
		&i.MediaType,
		&i.FileName,
		&i.FileUrl,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationSecs,
		&i.AltText,
		&i.IsPrimary,
		&i.SortOrder,
		&i.UploadedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageKey,
		&i.ContentHash,
	)
	return i, err
}

const mediaCheckPlayerExists = `-- name: MediaCheckPlayerExists :one

SELECT EXISTS(
    SELECT 1 FROM players
    WHERE id              = $1
      AND organization_id = $2
)::boolean
`

type MediaCheckPlayerExistsParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// ─────────────────────────────────────────────────────────────────────────────
// ENTITY EXISTENCE VALIDATION
// Validates that the target entity exists in the actor's org before upload.
// These are direct EXISTS queries to avoid importing other module packages.
// ─────────────────────────────────────────────────────────────────────────────
func (q *Queries) MediaCheckPlayerExists(ctx context.Context, arg MediaCheckPlayerExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, mediaCheckPlayerExists, arg.ID, arg.OrganizationID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const mediaCheckTeamExists = `-- name: MediaCheckTeamExists :one
SELECT EXISTS(
    SELECT 1 FROM teams
    WHERE id              = $1
      AND organization_id = $2
)::boolean
`

type MediaCheckTeamExistsParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) MediaCheckTeamExists(ctx context.Context, arg MediaCheckTeamExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, mediaCheckTeamExists, arg.ID, arg.OrganizationID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const mediaCheckTournamentExists = `-- name: MediaCheckTournamentExists :one
SELECT EXISTS(
    SELECT 1 FROM tournaments
    WHERE id              = $1
      AND organization_id = $2
)::boolean
`

type MediaCheckTournamentExistsParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) MediaCheckTournamentExists(ctx context.Context, arg MediaCheckTournamentExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, mediaCheckTournamentExists, arg.ID, arg.OrganizationID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setAttachmentAsPrimary = `-- name: SetAttachmentAsPrimary :one
UPDATE media_attachments
SET
    is_primary = TRUE,
    updated_at = NOW()
WHERE id              = $1
  AND organization_id = $2
RETURNING id, organization_id, entity_type, entity_id, media_type, file_name, file_url, file_size, mime_type, width, height, duration_secs, alt_text, is_primary, sort_order, uploaded_by, metadata, created_at, updated_at, storage_key, content_hash
`

type SetAttachmentAsPrimaryParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Called inside the primary-swap transaction AFTER unsetting the old primary.
func (q *Queries) SetAttachmentAsPrimary(ctx context.Context, arg SetAttachmentAsPrimaryParams) (MediaAttachment, error) {
	row := q.db.QueryRow(ctx, setAttachmentAsPrimary, arg.ID, arg.OrganizationID)
	var i MediaAttachment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EntityType,
		&i.EntityID,
		&i.MediaType,
		&i.FileName,
		&i.FileUrl,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationSecs,
		&i.AltText,
		&i.IsPrimary,
		&i.SortOrder,
		&i.UploadedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageKey,
		&i.ContentHash,
	)
	return i, err
}

const unsetPrimaryForEntity = `-- name: UnsetPrimaryForEntity :exec
UPDATE media_attachments
SET
    is_primary = FALSE,
    updated_at = NOW()
WHERE organization_id = $1
  AND entity_type     = $2
  AND entity_id       = $3
  AND is_primary      = TRUE
`

type UnsetPrimaryForEntityParams struct {
	OrganizationID pgtype.UUID     `json:"organization_id"`
	EntityType     MediaEntityType `json:"entity_type"`
	EntityID       pgtype.UUID     `json:"entity_id"`
}

// Clears the is_primary flag for all attachments belonging to an entity.
// Called inside the primary-swap transaction before setting the new primary.
func (q *Queries) UnsetPrimaryForEntity(ctx context.Context, arg UnsetPrimaryForEntityParams) error {
	_, err := q.db.Exec(ctx, unsetPrimaryForEntity, arg.OrganizationID, arg.EntityType, arg.EntityID)
	return err
}

const updateMediaAttachmentMeta = `-- name: UpdateMediaAttachmentMeta :one
UPDATE media_attachments
SET
    alt_text   = $3,
    sort_order = $4,
    updated_at = NOW()
WHERE id              = $1
  AND organization_id = $2
RETURNING id, organization_id, entity_type, entity_id, media_type, file_name, file_url, file_size, mime_type, width, height, duration_secs, alt_text, is_primary, sort_order, uploaded_by, metadata, created_at, updated_at, storage_key, content_hash
`

type UpdateMediaAttachmentMetaParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	AltText        *string     `json:"alt_text"`
	SortOrder      int16       `json:"sort_order"`
}

// Updates mutable metadata fields only (not storage fields or entity references).
func (q *Queries) UpdateMediaAttachmentMeta(ctx context.Context, arg UpdateMediaAttachmentMetaParams) (MediaAttachment, error) {
	row := q.db.QueryRow(ctx, updateMediaAttachmentMeta,
		arg.ID,
		arg.OrganizationID,
		arg.AltText,
		arg.SortOrder,
	)
	var i MediaAttachment
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EntityType,
		&i.EntityID,
		&i.MediaType,
		&i.FileName,
		&i.FileUrl,
		&i.FileSize,
		&i.MimeType,
		&i.Width,
		&i.Height,
		&i.DurationSecs,
		&i.AltText,
		&i.IsPrimary,
		&i.SortOrder,
		&i.UploadedBy,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageKey,
		&i.ContentHash,
	)
	return i, err
}
