// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

// Type of action recorded in audit_logs. create/update/delete: entity-scoped; old_data and new_data carry JSONB snapshots. login/logout: user-session events; entity_id will be NULL. permission_change: role or permission granted or revoked; old_data and new_data carry the before/after role assignment state.
type AuditAction string

const (
	AuditActionCreate           AuditAction = "create"
	AuditActionUpdate           AuditAction = "update"
	AuditActionDelete           AuditAction = "delete"
	AuditActionLogin            AuditAction = "login"
	AuditActionLogout           AuditAction = "logout"
	AuditActionPermissionChange AuditAction = "permission_change"
)

func (e *AuditAction) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditAction(s)
	case string:
		*e = AuditAction(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditAction: %T", src)
	}
	return nil
}

type NullAuditAction struct {
	AuditAction AuditAction `json:"audit_action"`
	Valid       bool        `json:"valid"` // Valid is true if AuditAction is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditAction) Scan(value interface{}) error {
	if value == nil {
		ns.AuditAction, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditAction.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditAction), nil
}

// Self-reported gender for user and player profiles. This field is always optional; the referencing column must be NULLable.
type Gender string

const (
	GenderMale           Gender = "male"
	GenderFemale         Gender = "female"
	GenderOther          Gender = "other"
	GenderPreferNotToSay Gender = "prefer_not_to_say"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender `json:"gender"`
	Valid  bool   `json:"valid"` // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

// Every possible recordable event during a match. Designed for kabaddi but structurally generic — sport-specific detail lives in the payload JSONB. This is the ONLY source of truth for scoring and player state. Never derive statistics from anywhere other than this event log. score_correction pairs with the is_cancelled flag and cancels_event_id FK on match_events to allow corrections without mutating or deleting prior events.
type MatchEventType string

const (
	MatchEventTypeMatchStarted      MatchEventType = "match_started"
	MatchEventTypeMatchEnded        MatchEventType = "match_ended"
	MatchEventTypeHalfStarted       MatchEventType = "half_started"
	MatchEventTypeHalfEnded         MatchEventType = "half_ended"
	MatchEventTypeTimeoutCalled     MatchEventType = "timeout_called"
	MatchEventTypeTimeoutEnded      MatchEventType = "timeout_ended"
	MatchEventTypeRaidAttempt       MatchEventType = "raid_attempt"
	MatchEventTypeRaidSuccessful    MatchEventType = "raid_successful"
	MatchEventTypeRaidEmpty         MatchEventType = "raid_empty"
	MatchEventTypeBonusPointAwarded MatchEventType = "bonus_point_awarded"
	MatchEventTypeTackleSuccessful  MatchEventType = "tackle_successful"
	MatchEventTypeSuperTackle       MatchEventType = "super_tackle"
	MatchEventTypeSuperRaid         MatchEventType = "super_raid"
	MatchEventTypeDoOrDieRaid       MatchEventType = "do_or_die_raid"
	MatchEventTypeAllOut            MatchEventType = "all_out"
	MatchEventTypePlayerOut         MatchEventType = "player_out"
	MatchEventTypePlayerRevived     MatchEventType = "player_revived"
	MatchEventTypePlayerSubstituted MatchEventType = "player_substituted"
	MatchEventTypePlayerInjured     MatchEventType = "player_injured"
	MatchEventTypePenaltyAwarded    MatchEventType = "penalty_awarded"
	MatchEventTypeScoreCorrection   MatchEventType = "score_correction"
)

func (e *MatchEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchEventType(s)
	case string:
		*e = MatchEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchEventType: %T", src)
	}
	return nil
}

type NullMatchEventType struct {
	MatchEventType MatchEventType `json:"match_event_type"`
	Valid          bool           `json:"valid"` // Valid is true if MatchEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchEventType) Scan(value interface{}) error {
	if value == nil {
		ns.MatchEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchEventType), nil
}

// Operational state of a match fixture. scheduled → live → completed is the normal flow. walkover sets winner_team_id/winner_player_id without match_events. abandoned: match started but ended without an official result. postponed: rescheduled; a new scheduled_at will be set.
type MatchStatus string

const (
	MatchStatusScheduled MatchStatus = "scheduled"
	MatchStatusLive      MatchStatus = "live"
	MatchStatusCompleted MatchStatus = "completed"
	MatchStatusCancelled MatchStatus = "cancelled"
	MatchStatusPostponed MatchStatus = "postponed"
	MatchStatusAbandoned MatchStatus = "abandoned"
	MatchStatusWalkover  MatchStatus = "walkover"
)

func (e *MatchStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchStatus(s)
	case string:
		*e = MatchStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchStatus: %T", src)
	}
	return nil
}

type NullMatchStatus struct {
	MatchStatus MatchStatus `json:"match_status"`
	Valid       bool        `json:"valid"` // Valid is true if MatchStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MatchStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchStatus), nil
}

// Discriminator in the polymorphic media_attachments reference. Paired with entity_id (UUID) to point at a row in the corresponding table. No database-level FK is possible for polymorphic references; referential integrity is enforced by the application service layer.
type MediaEntityType string

const (
	MediaEntityTypeOrganization MediaEntityType = "organization"
	MediaEntityTypeUser         MediaEntityType = "user"
	MediaEntityTypePlayer       MediaEntityType = "player"
	MediaEntityTypeTeam         MediaEntityType = "team"
	MediaEntityTypeTournament   MediaEntityType = "tournament"
	MediaEntityTypeMatch        MediaEntityType = "match"
)

func (e *MediaEntityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaEntityType(s)
	case string:
		*e = MediaEntityType(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaEntityType: %T", src)
	}
	return nil
}

type NullMediaEntityType struct {
	MediaEntityType MediaEntityType `json:"media_entity_type"`
	Valid           bool            `json:"valid"` // Valid is true if MediaEntityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaEntityType) Scan(value interface{}) error {
	if value == nil {
		ns.MediaEntityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaEntityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaEntityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaEntityType), nil
}

// Broad category of an uploaded media file. Pair with the mime_type column for precise format (image/webp, video/mp4, etc.). thumbnail is treated as distinct from image because it is auto-generated from a video and has different lifecycle and storage characteristics.
type MediaType string

const (
	MediaTypeImage     MediaType = "image"
	MediaTypeVideo     MediaType = "video"
	MediaTypeDocument  MediaType = "document"
	MediaTypeThumbnail MediaType = "thumbnail"
)

func (e *MediaType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaType(s)
	case string:
		*e = MediaType(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaType: %T", src)
	}
	return nil
}

type NullMediaType struct {
	MediaType MediaType `json:"media_type"`
	Valid     bool      `json:"valid"` // Valid is true if MediaType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaType) Scan(value interface{}) error {
	if value == nil {
		ns.MediaType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaType), nil
}

// Functional role of a person within a team. captain and vice_captain are on-field designations that can vary by tournament. coach, manager, and support_staff are non-playing roles tracked for full roster management.
type MembershipRole string

const (
	MembershipRolePlayer       MembershipRole = "player"
	MembershipRoleCaptain      MembershipRole = "captain"
	MembershipRoleViceCaptain  MembershipRole = "vice_captain"
	MembershipRoleCoach        MembershipRole = "coach"
	MembershipRoleManager      MembershipRole = "manager"
	MembershipRoleSupportStaff MembershipRole = "support_staff"
)

func (e *MembershipRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipRole(s)
	case string:
		*e = MembershipRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipRole: %T", src)
	}
	return nil
}

type NullMembershipRole struct {
	MembershipRole MembershipRole `json:"membership_role"`
	Valid          bool           `json:"valid"` // Valid is true if MembershipRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipRole) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipRole), nil
}

// Status of a player-to-team membership. transferred means the player moved to another team (left_at is set). released means the team ended the contract (left_at is set). The distinction matters for transfer window reporting.
type MembershipStatus string

const (
	MembershipStatusActive      MembershipStatus = "active"
	MembershipStatusInactive    MembershipStatus = "inactive"
	MembershipStatusTransferred MembershipStatus = "transferred"
	MembershipStatusReleased    MembershipStatus = "released"
)

func (e *MembershipStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembershipStatus(s)
	case string:
		*e = MembershipStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MembershipStatus: %T", src)
	}
	return nil
}

type NullMembershipStatus struct {
	MembershipStatus MembershipStatus `json:"membership_status"`
	Valid            bool             `json:"valid"` // Valid is true if MembershipStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembershipStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MembershipStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembershipStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembershipStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembershipStatus), nil
}

// Delivery channel for a notification. in_app: DB-persisted; read via API; sent_at = NOW() on drain. email: future transactional email; sent_at NULL until confirmed sent. webhook: future org-configured HTTP callback; sent_at NULL until confirmed.
type NotificationChannel string

const (
	NotificationChannelInApp   NotificationChannel = "in_app"
	NotificationChannelEmail   NotificationChannel = "email"
	NotificationChannelWebhook NotificationChannel = "webhook"
)

func (e *NotificationChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationChannel(s)
	case string:
		*e = NotificationChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationChannel: %T", src)
	}
	return nil
}

type NullNotificationChannel struct {
	NotificationChannel NotificationChannel `json:"notification_channel"`
	Valid               bool                `json:"valid"` // Valid is true if NotificationChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationChannel) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationChannel), nil
}

// Domain events that trigger notifications. match_*: lifecycle transitions on match fixtures. tournament_status_changed: any tournament status transition. registration_*: registration lifecycle changes.
type NotificationEventType string

const (
	NotificationEventTypeMatchCreated            NotificationEventType = "match_created"
	NotificationEventTypeMatchStarted            NotificationEventType = "match_started"
	NotificationEventTypeMatchCompleted          NotificationEventType = "match_completed"
	NotificationEventTypeMatchCancelled          NotificationEventType = "match_cancelled"
	NotificationEventTypeMatchAbandoned          NotificationEventType = "match_abandoned"
	NotificationEventTypeTournamentStatusChanged NotificationEventType = "tournament_status_changed"
	NotificationEventTypeRegistrationApproved    NotificationEventType = "registration_approved"
	NotificationEventTypeRegistrationRejected    NotificationEventType = "registration_rejected"
	NotificationEventTypeRegistrationWithdrawn   NotificationEventType = "registration_withdrawn"
)

func (e *NotificationEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationEventType(s)
	case string:
		*e = NotificationEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationEventType: %T", src)
	}
	return nil
}

type NullNotificationEventType struct {
	NotificationEventType NotificationEventType `json:"notification_event_type"`
	Valid                 bool                  `json:"valid"` // Valid is true if NotificationEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationEventType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationEventType), nil
}

// Operational status of an organization. A suspended organization cannot host tournaments or register for new events. All historical data is preserved intact.
type OrgStatus string

const (
	OrgStatusActive    OrgStatus = "active"
	OrgStatusInactive  OrgStatus = "inactive"
	OrgStatusSuspended OrgStatus = "suspended"
)

func (e *OrgStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrgStatus(s)
	case string:
		*e = OrgStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrgStatus: %T", src)
	}
	return nil
}

type NullOrgStatus struct {
	OrgStatus OrgStatus `json:"org_status"`
	Valid     bool      `json:"valid"` // Valid is true if OrgStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrgStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrgStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrgStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrgStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrgStatus), nil
}

// Categorical classification of an organization. Used for reporting and optional feature differentiation (e.g., federation-only tooling). Does not affect RBAC — use role_scope for access boundaries.
type OrgType string

const (
	OrgTypeClub        OrgType = "club"
	OrgTypeFederation  OrgType = "federation"
	OrgTypeSchool      OrgType = "school"
	OrgTypeCorporate   OrgType = "corporate"
	OrgTypeIndependent OrgType = "independent"
)

func (e *OrgType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrgType(s)
	case string:
		*e = OrgType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrgType: %T", src)
	}
	return nil
}

type NullOrgType struct {
	OrgType OrgType `json:"org_type"`
	Valid   bool    `json:"valid"` // Valid is true if OrgType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrgType) Scan(value interface{}) error {
	if value == nil {
		ns.OrgType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrgType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrgType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrgType), nil
}

// Determines whether tournament participants are teams or individual players. team: team_id is set in registrations; home_team_id/away_team_id set in matches. individual: player_id is set in registrations; home_player_id/away_player_id set in matches.
type ParticipantType string

const (
	ParticipantTypeTeam       ParticipantType = "team"
	ParticipantTypeIndividual ParticipantType = "individual"
)

func (e *ParticipantType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParticipantType(s)
	case string:
		*e = ParticipantType(s)
	default:
		return fmt.Errorf("unsupported scan type for ParticipantType: %T", src)
	}
	return nil
}

type NullParticipantType struct {
	ParticipantType ParticipantType `json:"participant_type"`
	Valid           bool            `json:"valid"` // Valid is true if ParticipantType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParticipantType) Scan(value interface{}) error {
	if value == nil {
		ns.ParticipantType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParticipantType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParticipantType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParticipantType), nil
}

// Athletic lifecycle state of a player profile. injured and suspended are intentionally separate from inactive so roster eligibility checks can distinguish voluntary vs forced unavailability. retired records are kept permanently for historical statistics.
type PlayerStatus string

const (
	PlayerStatusActive    PlayerStatus = "active"
	PlayerStatusInactive  PlayerStatus = "inactive"
	PlayerStatusInjured   PlayerStatus = "injured"
	PlayerStatusSuspended PlayerStatus = "suspended"
	PlayerStatusRetired   PlayerStatus = "retired"
)

func (e *PlayerStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlayerStatus(s)
	case string:
		*e = PlayerStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PlayerStatus: %T", src)
	}
	return nil
}

type NullPlayerStatus struct {
	PlayerStatus PlayerStatus `json:"player_status"`
	Valid        bool         `json:"valid"` // Valid is true if PlayerStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlayerStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PlayerStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlayerStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlayerStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlayerStatus), nil
}

// Lifecycle state of a tournament registration. pending: submitted, awaiting organiser review. approved: confirmed participant; counts against max_participants. rejected: denied by the organiser. withdrawn: voluntarily pulled out by the registrant before the tournament starts. disqualified: removed after the tournament began; results may be voided.
type RegistrationStatus string

const (
	RegistrationStatusPending      RegistrationStatus = "pending"
	RegistrationStatusApproved     RegistrationStatus = "approved"
	RegistrationStatusRejected     RegistrationStatus = "rejected"
	RegistrationStatusWithdrawn    RegistrationStatus = "withdrawn"
	RegistrationStatusDisqualified RegistrationStatus = "disqualified"
)

func (e *RegistrationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RegistrationStatus(s)
	case string:
		*e = RegistrationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RegistrationStatus: %T", src)
	}
	return nil
}

type NullRegistrationStatus struct {
	RegistrationStatus RegistrationStatus `json:"registration_status"`
	Valid              bool               `json:"valid"` // Valid is true if RegistrationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRegistrationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RegistrationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RegistrationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRegistrationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RegistrationStatus), nil
}

// Boundary within which a role is valid. platform roles have a NULL organization_id and grant cross-tenant access. organization roles are always paired with a non-NULL organization_id. tournament scope is reserved for future per-tournament permission grants.
type RoleScope string

const (
	RoleScopePlatform     RoleScope = "platform"
	RoleScopeOrganization RoleScope = "organization"
	RoleScopeTournament   RoleScope = "tournament"
)

func (e *RoleScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleScope(s)
	case string:
		*e = RoleScope(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleScope: %T", src)
	}
	return nil
}

type NullRoleScope struct {
	RoleScope RoleScope `json:"role_scope"`
	Valid     bool      `json:"valid"` // Valid is true if RoleScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleScope) Scan(value interface{}) error {
	if value == nil {
		ns.RoleScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleScope), nil
}

// Operational status of a team. disbanded teams are retained because match history and rankings reference them. Hard deletion of a disbanded team would corrupt historical records.
type TeamStatus string

const (
	TeamStatusActive    TeamStatus = "active"
	TeamStatusInactive  TeamStatus = "inactive"
	TeamStatusDisbanded TeamStatus = "disbanded"
)

func (e *TeamStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamStatus(s)
	case string:
		*e = TeamStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamStatus: %T", src)
	}
	return nil
}

type NullTeamStatus struct {
	TeamStatus TeamStatus `json:"team_status"`
	Valid      bool       `json:"valid"` // Valid is true if TeamStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TeamStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamStatus), nil
}

// Structural format determining how brackets and standings are computed. league: full points table (home/away or single-leg). knockout: single-elimination bracket. group_knockout: group stage followed by knockout rounds. round_robin: every participant plays every other once. double_elimination: two losses required for elimination. Format-specific config lives in tournaments.settings JSONB.
type TournamentFormat string

const (
	TournamentFormatLeague            TournamentFormat = "league"
	TournamentFormatKnockout          TournamentFormat = "knockout"
	TournamentFormatGroupKnockout     TournamentFormat = "group_knockout"
	TournamentFormatRoundRobin        TournamentFormat = "round_robin"
	TournamentFormatDoubleElimination TournamentFormat = "double_elimination"
)

func (e *TournamentFormat) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TournamentFormat(s)
	case string:
		*e = TournamentFormat(s)
	default:
		return fmt.Errorf("unsupported scan type for TournamentFormat: %T", src)
	}
	return nil
}

type NullTournamentFormat struct {
	TournamentFormat TournamentFormat `json:"tournament_format"`
	Valid            bool             `json:"valid"` // Valid is true if TournamentFormat is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTournamentFormat) Scan(value interface{}) error {
	if value == nil {
		ns.TournamentFormat, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TournamentFormat.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTournamentFormat) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TournamentFormat), nil
}

// Lifecycle state of a tournament. Transitions are one-way in application logic. draft: being configured, not yet public. registration_open: accepting entries. registration_closed: entries locked, bracket being finalised. ongoing: matches are being played. completed: all matches done, results final. cancelled: abandoned; registrations are voided by application logic.
type TournamentStatus string

const (
	TournamentStatusDraft              TournamentStatus = "draft"
	TournamentStatusRegistrationOpen   TournamentStatus = "registration_open"
	TournamentStatusRegistrationClosed TournamentStatus = "registration_closed"
	TournamentStatusOngoing            TournamentStatus = "ongoing"
	TournamentStatusCompleted          TournamentStatus = "completed"
	TournamentStatusCancelled          TournamentStatus = "cancelled"
)

func (e *TournamentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TournamentStatus(s)
	case string:
		*e = TournamentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TournamentStatus: %T", src)
	}
	return nil
}

type NullTournamentStatus struct {
	TournamentStatus TournamentStatus `json:"tournament_status"`
	Valid            bool             `json:"valid"` // Valid is true if TournamentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTournamentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TournamentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TournamentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTournamentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TournamentStatus), nil
}

// Lifecycle states for a user account. pending_verification is set on registration until the email is confirmed. suspended is set administratively and blocks all authenticated access.
type UserStatus string

const (
	UserStatusActive              UserStatus = "active"
	UserStatusInactive            UserStatus = "inactive"
	UserStatusSuspended           UserStatus = "suspended"
	UserStatusPendingVerification UserStatus = "pending_verification"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

// Immutable system-wide audit ledger. Every significant data mutation, login event, and permission change produces a row. No UPDATE or DELETE is ever performed here — rows are written once and never touched again. When row count exceeds 50M, add monthly range partitioning by created_at.
type AuditLog struct {
	ID pgtype.UUID `json:"id"`
	// The org context in which the action occurred. NULL for platform-level actions (super-admin login, platform role grants). SET NULL on org deletion: audit records are retained regardless.
	OrganizationID pgtype.UUID `json:"organization_id"`
	// The user who performed the action. NULL if the action was system-initiated (scheduled job, webhook, etc.). SET NULL on user deletion: audit records are retained regardless.
	UserID pgtype.UUID `json:"user_id"`
	Action AuditAction `json:"action"`
	// Table or domain name of the affected entity (e.g. tournaments, matches, players). Use the exact table name for consistency.
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	// JSONB snapshot of the entity state BEFORE an update or delete. NULL for create, login, and logout actions.
	OldData []byte `json:"old_data"`
	// JSONB snapshot of the entity state AFTER a create or update. NULL for delete, login, and logout actions.
	NewData []byte `json:"new_data"`
	// INET type: stores both IPv4 and IPv6. Captured from the request context at write time.
	IpAddress *netip.Addr        `json:"ip_address"`
	UserAgent *string            `json:"user_agent"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Single-use email verification tokens. Stores a SHA-256 hash of the raw token — the raw value is never persisted. A token is valid when: used_at IS NULL AND expires_at > NOW(). Expired and used rows are cleaned up by a periodic background job.
type EmailVerificationToken struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	// SHA-256 hex-encoded hash of the raw token sent to the user. Lookup: WHERE token_hash = encode(digest($raw_token, 'sha256'), 'hex').
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// Set to NOW() the first time the token is successfully consumed. NULL means the token is still valid (pending use).
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Individual match fixture within a tournament. organization_id is denormalized from tournaments.organization_id to avoid a JOIN on every match-list query — must always equal the parent tournament org. Participant columns are NULL for bracket matches whose opponents are TBD. winner_* columns are set at completion: they are a final-state conclusion, not a running statistic, so denormalization is justified here.
type Match struct {
	ID           pgtype.UUID `json:"id"`
	TournamentID pgtype.UUID `json:"tournament_id"`
	// Denormalized from tournaments.organization_id. The application must keep this in sync with the parent tournament.
	OrganizationID pgtype.UUID `json:"organization_id"`
	// Numeric round index (1, 2, 3…). Used for sorting and bracket logic. Use round_name for display strings (Quarter Final, Semi Final, Final).
	RoundNumber *int16  `json:"round_number"`
	RoundName   *string `json:"round_name"`
	// Sequential match identifier within the tournament. Determines display ordering on the fixture list.
	MatchNumber    *int16             `json:"match_number"`
	HomeTeamID     pgtype.UUID        `json:"home_team_id"`
	AwayTeamID     pgtype.UUID        `json:"away_team_id"`
	HomePlayerID   pgtype.UUID        `json:"home_player_id"`
	AwayPlayerID   pgtype.UUID        `json:"away_player_id"`
	Venue          *string            `json:"venue"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
	Status         MatchStatus        `json:"status"`
	WinnerTeamID   pgtype.UUID        `json:"winner_team_id"`
	WinnerPlayerID pgtype.UUID        `json:"winner_player_id"`
	// TRUE when one side did not appear. The winner is awarded without match_events. chk_matches_walkover_has_winner enforces that winner_* must be set.
	IsWalkover bool    `json:"is_walkover"`
	Notes      *string `json:"notes"`
	// Sport-specific match configuration: half duration in seconds, max timeouts per team, max substitutions, super raid rule variant, etc.
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Final home participant score. Snapshotted atomically inside the live → completed transition transaction under a FOR UPDATE lock. Reflects the effective event log at the exact moment of completion — the log is frozen by the match-status check in CreateWithAudit, so no correction can alter this value after it is written. Always 0 for walkovers (no events produce points) and for any non-completed match status. Standings must read this column, never match_events, for completed match scores.
	HomeScore int32 `json:"home_score"`
	// Final away participant score. See home_score for the full contract.
	AwayScore int32 `json:"away_score"`
	// Bracket edge: the match this fixture's winner advances to. NULL for finals, round-robin, league, and group-stage matches. ON DELETE SET NULL — a hard tournament delete cascades; matches are otherwise soft-cancelled, never deleted.
	NextMatchID pgtype.UUID `json:"next_match_id"`
	// Which slot of next_match_id this winner fills: 1 = home, 2 = away. The slot is fixed per feeder so propagation writes exactly one deterministic slot — this is what makes winner propagation idempotent and double-write-safe.
	NextMatchSlot *int16 `json:"next_match_slot"`
	// Group identifier (e.g. "A", "B") for group_knockout group-stage matches. Reserved for the FE-8C group_knockout path; no resolution logic in FE-8B.
	GroupLabel *string `json:"group_label"`
}

// Append-only immutable event log. The single source of truth for all in-match data. Every point, player state change, and lifecycle transition is a row here. No UPDATE or DELETE is ever performed. score_correction events invalidate prior events via cancels_event_id without mutating them. All statistics (team scores, player raid counts, tackle rates) must be derived from this table — never stored redundantly in other tables.
type MatchEvent struct {
	ID             pgtype.UUID `json:"id"`
	MatchID        pgtype.UUID `json:"match_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	// Monotonically increasing integer per match, starting at 1. Uniquely orders events within a match (guaranteed by uq_match_events_sequence). Application must hold a row-level lock on the parent match row during insert to safely compute MAX(sequence_number) + 1 under concurrent scorers.
	SequenceNumber int64          `json:"sequence_number"`
	EventType      MatchEventType `json:"event_type"`
	TeamID         pgtype.UUID    `json:"team_id"`
	PlayerID       pgtype.UUID    `json:"player_id"`
	Period         *int16         `json:"period"`
	// Elapsed match clock in seconds at the moment of the event. E.g. 245 = 4 minutes 5 seconds into the half. NULL for lifecycle events (match_started, half_ended, etc.) where a clock value is not meaningful.
	ClockSeconds *int32 `json:"clock_seconds"`
	// Event-type-specific structured data. Validated at the application layer. Examples by event type: raid_successful  → {"points": 2, "defenders_tagged": ["<uuid>", "<uuid>"]} tackle_successful → {"tacklers": ["<uuid>"], "raider_out": true} super_tackle     → {"tacklers": ["<uuid>"], "points": 2} all_out          → {"team_id": "<uuid>", "bonus_points": 2} player_substituted → {"out_player_id": "<uuid>", "in_player_id": "<uuid>"} score_correction → {"reason": "wrong team credited", "original_payload": {...}}
	Payload []byte `json:"payload"`
	// The scorer or referee who entered this event. SET NULL on user deletion: the event record is retained regardless.
	RecordedBy pgtype.UUID        `json:"recorded_by"`
	RecordedAt pgtype.Timestamptz `json:"recorded_at"`
	// Points to the event this record invalidates. Set only on score_correction events. The referenced event is never mutated — immutability is fully preserved. To get the effective event log: exclude events whose id appears in any cancels_event_id within the same match.
	CancelsEventID pgtype.UUID        `json:"cancels_event_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Polymorphic media store. (entity_type, entity_id) is a soft FK to any domain entity. No database-level FK is possible across multiple tables: referential integrity is enforced by the application service layer. When a parent entity is deleted, the application must clean up its attachments. Physical file deletion from object storage is also the application's responsibility.
type MediaAttachment struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	// Discriminator for the polymorphic reference. Paired with entity_id to identify the owning row in the correct domain table.
	EntityType MediaEntityType `json:"entity_type"`
	// UUID of the entity this attachment belongs to. No DB-level FK — validated against the correct table by the service layer.
	EntityID     pgtype.UUID `json:"entity_id"`
	MediaType    MediaType   `json:"media_type"`
	FileName     string      `json:"file_name"`
	FileUrl      string      `json:"file_url"`
	FileSize     *int64      `json:"file_size"`
	MimeType     *string     `json:"mime_type"`
	Width        *int16      `json:"width"`
	Height       *int16      `json:"height"`
	DurationSecs *int32      `json:"duration_secs"`
	// Accessibility text for images. Stored here rather than in a CMS.
	AltText *string `json:"alt_text"`
	// TRUE if this is the featured attachment for the entity (profile photo, team logo, tournament banner). At most one primary attachment per (entity_type, entity_id) should be active. Enforced by the application layer, not a DB constraint, to allow atomic swaps.
	IsPrimary bool `json:"is_primary"`
	// Display ordering within an entity's attachment gallery. Lower values appear first. Default 0.
	SortOrder  int16       `json:"sort_order"`
	UploadedBy pgtype.UUID `json:"uploaded_by"`
	// CDN metadata, processing status, thumbnail variants, focal point hints, etc. Schema-free; validated at the application layer.
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Canonical object path in the storage backend (e.g. S3 key). Source of truth — independent of CDN domain. file_url is derived from storage_key + the configured CDN base URL at insert time. When the CDN changes, update file_url from this column — not the reverse.
	StorageKey string `json:"storage_key"`
	// SHA-256 hex digest of the raw uploaded file bytes, computed before any processing. Used for duplicate detection: if (entity_type, entity_id, content_hash) already exists, the existing attachment is returned instead of creating a duplicate. Also used for integrity verification.
	ContentHash string `json:"content_hash"`
}

// Personal notification inbox. Written ONLY by DrainOutbox — never by domain code directly. Every row is scoped to one user within one organization. UNIQUE (outbox_id, user_id, channel) ensures a drain retry is idempotent.
type Notification struct {
	ID             pgtype.UUID           `json:"id"`
	OrganizationID pgtype.UUID           `json:"organization_id"`
	UserID         pgtype.UUID           `json:"user_id"`
	OutboxID       pgtype.UUID           `json:"outbox_id"`
	Channel        NotificationChannel   `json:"channel"`
	EventType      NotificationEventType `json:"event_type"`
	EntityType     string                `json:"entity_type"`
	EntityID       pgtype.UUID           `json:"entity_id"`
	Payload        []byte                `json:"payload"`
	ReadAt         pgtype.Timestamptz    `json:"read_at"`
	// Delivery timestamp. Contract: in_app → set to NOW() on drain insert; email/webhook → NULL until the respective delivery worker confirms send.
	SentAt pgtype.Timestamptz `json:"sent_at"`
	// Soft-delete timestamp. NULL = visible. Set by DELETE endpoint. Deleted notifications are excluded from list queries but retained for audit.
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Number of email delivery attempts claimed by the EmailWorker. Incremented at claim time (before delivery). Capped at max_attempts (3). Applies only to channel = 'email'; unused for in_app.
	AttemptCount int32 `json:"attempt_count"`
	// Timestamp of the most recent delivery attempt claim. Used to order the worker claim queue (oldest-first) and calculate retry windows.
	LastAttemptedAt pgtype.Timestamptz `json:"last_attempted_at"`
	// Soft lease expiry set by the EmailWorker when claiming a row. Prevents concurrent workers from double-delivering the same email. On successful delivery: superseded by sent_at. On failure: reset to NOW() + retry_delay by RecordEmailDeliveryFailure. On worker crash: expires naturally so another worker can retry.
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
	// Set to TRUE after max_attempts delivery attempts all fail. Rows with failed_permanently = TRUE are never retried automatically; they require manual intervention (e.g., admin reset or investigation).
	FailedPermanently bool `json:"failed_permanently"`
}

// Transactional outbox for domain-event notifications. Rows are written inside domain transactions (matches, tournaments, registrations). DrainOutbox reads pending rows (processed_at IS NULL) using FOR UPDATE SKIP LOCKED and fans them out into the notifications table. All rows are retained permanently for auditability.
type NotificationOutbox struct {
	ID             pgtype.UUID           `json:"id"`
	OrganizationID pgtype.UUID           `json:"organization_id"`
	EventType      NotificationEventType `json:"event_type"`
	ActorID        pgtype.UUID           `json:"actor_id"`
	EntityType     string                `json:"entity_type"`
	EntityID       pgtype.UUID           `json:"entity_id"`
	Payload        []byte                `json:"payload"`
	// Set to NOW() by DrainOutbox after all notifications for this entry have been inserted. NULL = pending. Once set, the entry is never modified again.
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Per-user notification preferences within an organization. A missing row means notifications are enabled (opt-out model). Writes use UPSERT (last-writer-wins) on (organization_id, user_id, event_type, channel).
type NotificationPreference struct {
	ID             pgtype.UUID           `json:"id"`
	OrganizationID pgtype.UUID           `json:"organization_id"`
	UserID         pgtype.UUID           `json:"user_id"`
	EventType      NotificationEventType `json:"event_type"`
	Channel        NotificationChannel   `json:"channel"`
	Enabled        bool                  `json:"enabled"`
	CreatedAt      pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz    `json:"updated_at"`
}

// Root multi-tenant entity. Every business-domain table carries organization_id as a FK. Deleting an organization cascades to all child records. Super-admin users exist outside any organization via platform-scoped roles.
type Organization struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	// URL-safe unique identifier. Lowercase alphanumeric and hyphens only. Used in public-facing API paths and routes. Immutable after creation.
	Slug        string    `json:"slug"`
	Description *string   `json:"description"`
	Type        OrgType   `json:"type"`
	Status      OrgStatus `json:"status"`
	LogoUrl     *string   `json:"logo_url"`
	Website     *string   `json:"website"`
	Email       *string   `json:"email"`
	Phone       *string   `json:"phone"`
	// ISO 3166-1 alpha-2 country code (e.g. IN for India, US for United States). Two uppercase letters. Validated by chk_organizations_country.
	Country *string `json:"country"`
	City    *string `json:"city"`
	// Org-level configuration: feature flags, allowed sports, branding overrides. Schema-free to avoid migrations for per-org customisation. Structure is validated and documented at the application layer.
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Single-use password reset tokens. Stores only the SHA-256 hash of the raw token — the raw token is emailed to the user and never stored here. A token is valid when: used_at IS NULL AND expires_at > NOW(). Expired and used rows are removed by the background cleanup scheduler.
type PasswordResetToken struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	// SHA-256 hex-encoded hash of the raw reset token. Lookup: WHERE token_hash = encode(digest($raw, 'sha256'), 'hex').
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// Set to NOW() when the token is consumed by a successful password reset. Also set on all sibling tokens for the same user when any reset completes, preventing stale tokens from being used after the password has changed.
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Atomic capability definitions. Deployed by application code; not user-editable. slug convention: <resource>.<action> (e.g. tournament.create, match.score). resource and action are kept as separate columns for fine-grained RBAC queries.
type Permission struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
	// Dot-notation identifier used in application authorization checks. Format: <resource>.<action> (lowercase, underscores allowed).
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
	// Domain entity this permission applies to (e.g. tournament, match, player).
	Resource string `json:"resource"`
	// Operation being permitted. Constrained to a known vocabulary by CHECK constraint.
	Action    string             `json:"action"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Athletic profile scoped to an organization. Decoupled from users: one user can have multiple player profiles across orgs, and historical/scouted players may have no platform account at all. ON DELETE CASCADE: removing an org removes all its player records. ON DELETE SET NULL on user_id: deleting a user account does not erase the player record.
type Player struct {
	ID pgtype.UUID `json:"id"`
	// Nullable from GP-1. NULL = global, user-owned profile with no origin org. Non-NULL = legacy org-created profile. Ownership semantics removed in a later phase.
	OrganizationID pgtype.UUID `json:"organization_id"`
	// Links this player profile to a platform user account. NULL for unregistered or historical players. One user may have N player profiles (different orgs, different sports).
	UserID pgtype.UUID `json:"user_id"`
	// Public-facing name shown on scoreboards, brackets, and profiles. May differ from the linked user first_name + last_name (e.g. a sporting alias).
	DisplayName  string  `json:"display_name"`
	JerseyNumber *string `json:"jersey_number"`
	// Sport-specific playing position. Free text to support all sports. Examples: raider, all-rounder, left-defender (kabaddi); striker (football).
	Position     *string `json:"position"`
	HeightCm     *int16  `json:"height_cm"`
	WeightKg     *int16  `json:"weight_kg"`
	DominantHand *string `json:"dominant_hand"`
	// ISO 3166-1 alpha-2 country code (e.g. IN, US). Two uppercase letters.
	Nationality *string      `json:"nationality"`
	DateOfBirth pgtype.Date  `json:"date_of_birth"`
	Status      PlayerStatus `json:"status"`
	Bio         *string      `json:"bio"`
	// Sport-specific attributes that do not fit the fixed schema: raid style (kabaddi), batting order (cricket), preferred formation role, etc.
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// public | unlisted | private. Default private (privacy-safe). Consumed by global profile reads.
	Visibility string `json:"visibility"`
	// Non-NULL marks a non-canonical duplicate identity (legacy multi-org rows for one user). Archived rows are read-only, non-ranking, retained for history. Never merged (no-claim policy).
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

// Final standings result for one player in one completed tournament. Snapshotted at tournament completion. Source for all-time player rankings.
type PlayerTournamentStat struct {
	ID             pgtype.UUID        `json:"id"`
	PlayerID       pgtype.UUID        `json:"player_id"`
	TournamentID   pgtype.UUID        `json:"tournament_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Position       int32              `json:"position"`
	MatchesPlayed  int32              `json:"matches_played"`
	MatchesWon     int32              `json:"matches_won"`
	MatchesDrawn   int32              `json:"matches_drawn"`
	MatchesLost    int32              `json:"matches_lost"`
	Points         int32              `json:"points"`
	ScoreFor       int32              `json:"score_for"`
	ScoreAgainst   int32              `json:"score_against"`
	SnapshottedAt  pgtype.Timestamptz `json:"snapshotted_at"`
}

// JWT refresh token revocation store. Stores a hash of the raw token — the raw token is never persisted. A token is valid when: revoked_at IS NULL AND expires_at > NOW(). Expired and revoked rows are cleaned up by a periodic background job.
type RefreshToken struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	// SHA-256 hash of the raw refresh token. Lookup: WHERE token_hash = encode(digest($raw_token, 'sha256'), 'hex').
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	// Set to NOW() when the token is explicitly invalidated (logout, password change). NULL means the token has not been revoked yet.
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	IpAddress *netip.Addr        `json:"ip_address"`
	UserAgent *string            `json:"user_agent"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// UUID of the token issued to replace this one during rotation. NULL when the token has not been rotated (active or explicitly revoked). Non-NULL when the token was superseded by a rotation. Used exclusively as a boolean state marker — the value is never followed as a reference. Not a foreign key by design.
	SuccessorID pgtype.UUID `json:"successor_id"`
}

// Named permission groups. Platform roles (scope = platform) have organization_id = NULL and are reserved for super-admins. Org roles are always paired with a non-NULL organization_id. is_system = TRUE marks roles seeded by migrations that cannot be deleted via the API.
type Role struct {
	ID pgtype.UUID `json:"id"`
	// NULL for platform-scoped roles. Non-NULL for org-scoped roles. Enforced by chk_roles_platform_no_org.
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	Slug           string      `json:"slug"`
	Description    *string     `json:"description"`
	Scope          RoleScope   `json:"scope"`
	// Marks roles seeded by migrations (e.g. org_owner, scorer, viewer). The API must refuse to delete or rename system roles.
	IsSystem  bool               `json:"is_system"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Many-to-many join between roles and permissions. Assigning a role to a user grants all permissions linked to that role. CASCADE on both sides: deleting a role or permission cleans up the join rows.
type RolePermission struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

// A team entity scoped to an organization. slug is unique within the org. disbanded teams are retained permanently for historical match and ranking records: hard-deleting a disbanded team would corrupt match winner references.
type Team struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	// Abbreviation for scoreboards and brackets (e.g. MUM for Mumbai Raiders). Constrained to 2–10 characters. Used where full team name does not fit.
	ShortName   *string `json:"short_name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
	LogoUrl     *string `json:"logo_url"`
	HomeCity    *string `json:"home_city"`
	HomeVenue   *string `json:"home_venue"`
	FoundedYear *int16  `json:"founded_year"`
	// Hex color code for the primary kit color (e.g. #FF5733). Used in UI theming, bracket displays, and charts. Validated as #RRGGBB.
	PrimaryColor *string `json:"primary_color"`
	// Hex color code for the secondary kit color. Same format as primary_color.
	SecondaryColor *string    `json:"secondary_color"`
	Status         TeamStatus `json:"status"`
	// Sport-specific or org-specific team attributes. Examples: home_state, social_media_handles, kit_supplier, achievements.
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Tracks a player belonging to a team over a specific time window. No UNIQUE(team_id, player_id): players can rejoin teams, each stint is a new row. transferred and released statuses both require left_at to be set. Application logic determines the "current" membership by querying WHERE status = 'active' ORDER BY joined_at DESC LIMIT 1.
type TeamMembership struct {
	ID       pgtype.UUID `json:"id"`
	TeamID   pgtype.UUID `json:"team_id"`
	PlayerID pgtype.UUID `json:"player_id"`
	// Functional role within this team. captain/vice_captain are on-field designations and may be updated per tournament without changing the membership record.
	Role MembershipRole `json:"role"`
	// Overrides players.jersey_number for this team specifically. A player may wear different numbers across teams.
	JerseyNumber *string            `json:"jersey_number"`
	Status       MembershipStatus   `json:"status"`
	JoinedAt     pgtype.Timestamptz `json:"joined_at"`
	// The date and time the player left this team. NULL means the player is currently an active member. Always set when transitioning to transferred or released.
	LeftAt pgtype.Timestamptz `json:"left_at"`
	// Internal notes for the org admin (e.g. reason for release, loan details). Not shown to the public.
	Notes     *string            `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	// Tenant scope: must equal both teams.organization_id and players.organization_id for this membership row. Enforced by trg_team_memberships_org_consistency.
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Final standings result for one team in one completed tournament. Snapshotted at tournament completion. Source for all-time team rankings.
type TeamTournamentStat struct {
	ID             pgtype.UUID        `json:"id"`
	TeamID         pgtype.UUID        `json:"team_id"`
	TournamentID   pgtype.UUID        `json:"tournament_id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	Position       int32              `json:"position"`
	MatchesPlayed  int32              `json:"matches_played"`
	MatchesWon     int32              `json:"matches_won"`
	MatchesDrawn   int32              `json:"matches_drawn"`
	MatchesLost    int32              `json:"matches_lost"`
	Points         int32              `json:"points"`
	ScoreFor       int32              `json:"score_for"`
	ScoreAgainst   int32              `json:"score_against"`
	SnapshottedAt  pgtype.Timestamptz `json:"snapshotted_at"`
}

// A tournament hosted by an organization. slug is unique within the org. Status transitions are one-way in application logic: draft → registration_open → registration_closed → ongoing → completed. Any state → cancelled is always permitted.
type Tournament struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	Slug           string      `json:"slug"`
	Description    *string     `json:"description"`
	// Free-text sport identifier (e.g. kabaddi, cricket, football, badminton). Intentionally TEXT rather than ENUM: adding a new sport requires no schema migration. Normalise casing at the application layer (lowercase, trimmed).
	Sport string `json:"sport"`
	// Structural format determining how brackets and standings are computed. Format-specific config (group sizes, legs, tiebreaker rules) lives in settings JSONB.
	Format          TournamentFormat `json:"format"`
	ParticipantType ParticipantType  `json:"participant_type"`
	Status          TournamentStatus `json:"status"`
	BannerUrl       *string          `json:"banner_url"`
	PrizePool       pgtype.Numeric   `json:"prize_pool"`
	// ISO 4217 three-letter currency code (e.g. INR, USD). Validated as three uppercase letters.
	Currency             string             `json:"currency"`
	MaxParticipants      *int16             `json:"max_participants"`
	MinParticipants      *int16             `json:"min_participants"`
	RegistrationOpensAt  pgtype.Timestamptz `json:"registration_opens_at"`
	RegistrationClosesAt pgtype.Timestamptz `json:"registration_closes_at"`
	StartsAt             pgtype.Timestamptz `json:"starts_at"`
	EndsAt               pgtype.Timestamptz `json:"ends_at"`
	Venue                *string            `json:"venue"`
	City                 *string            `json:"city"`
	Country              *string            `json:"country"`
	Rules                *string            `json:"rules"`
	// Format-specific configuration validated at the application layer. Examples: {"groups": 4, "teams_per_group": 3, "tiebreaker": ["points","nrr"]} for group_knockout; {"legs": 2} for league; {"bo": 3} for best-of-3 knockout.
	Settings []byte `json:"settings"`
	// User who created this tournament. SET NULL on user deletion: the tournament is retained regardless.
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Records a team or individual player entering a tournament. Exactly one of team_id / player_id must be non-NULL (chk_treg_one_participant). organization_id is the registrant's org — not necessarily the tournament host org. This distinction matters for cross-org tournaments (e.g. a league with multiple clubs).
type TournamentRegistration struct {
	ID           pgtype.UUID `json:"id"`
	TournamentID pgtype.UUID `json:"tournament_id"`
	// The organization that owns the registering team or player. Distinct from the tournament's organization_id. Enables queries like "all registrations submitted by org X".
	OrganizationID pgtype.UUID `json:"organization_id"`
	TeamID         pgtype.UUID `json:"team_id"`
	PlayerID       pgtype.UUID `json:"player_id"`
	// Seeding position assigned by the tournament organiser after registration closes. Determines bracket placement for knockout formats. NULL until explicitly set; positive integer only.
	SeedNumber   *int16             `json:"seed_number"`
	Status       RegistrationStatus `json:"status"`
	RegisteredBy pgtype.UUID        `json:"registered_by"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
	ApprovedBy   pgtype.UUID        `json:"approved_by"`
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
	Notes        *string            `json:"notes"`
	// Extra registration data: squad list submission, payment reference, documents, etc. Structure is tournament-specific and validated at the application layer.
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Platform-level identity. One account per human being. Users are not directly scoped to an organization: membership is managed via the user_organization_roles join table. Super-admin users have platform-scoped roles with organization_id = NULL.
type User struct {
	ID pgtype.UUID `json:"id"`
	// Globally unique email address. Primary login identifier. Must be verified before status transitions to active.
	Email string `json:"email"`
	// Globally unique display handle. 3–30 chars, alphanumeric and underscores only. Used in public profiles and @mentions.
	Username string `json:"username"`
	// bcrypt hash of the user password. Never store plaintext. Minimum bcrypt cost factor: 12.
	PasswordHash string      `json:"password_hash"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
	Phone        *string     `json:"phone"`
	AvatarUrl    *string     `json:"avatar_url"`
	DateOfBirth  pgtype.Date `json:"date_of_birth"`
	// Self-reported, optional. NULL means not provided — distinct from prefer_not_to_say which means the user explicitly declined.
	Gender          *Gender            `json:"gender"`
	Status          UserStatus         `json:"status"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	LastLoginAt     pgtype.Timestamptz `json:"last_login_at"`
	// INET type stores both IPv4 and IPv6 addresses natively. Used for security auditing and anomaly detection (e.g., new-country login).
	LastLoginIp *netip.Addr        `json:"last_login_ip"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Grants a user a role within a specific organization. A user can hold multiple roles in the same org (e.g. scorer + media_manager). ON DELETE RESTRICT on role_id: a role cannot be deleted while assigned to any user. Use this table as the authority for all authorization decisions.
type UserOrganizationRole struct {
	ID             pgtype.UUID `json:"id"`
	UserID         pgtype.UUID `json:"user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	RoleID         pgtype.UUID `json:"role_id"`
	// The admin who granted this role assignment. SET NULL on user deletion: the grant record is retained regardless.
	GrantedBy pgtype.UUID        `json:"granted_by"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
	// Optional expiry for time-limited grants (e.g. guest scorer for one tournament). The application must enforce this — no automatic revocation occurs at the DB layer.
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Endpoint-centric delivery queue for webhook notifications. One row per (outbox_id, endpoint_id). Fan-out performed by DrainOutbox.
type WebhookDelivery struct {
	ID                pgtype.UUID           `json:"id"`
	OrganizationID    pgtype.UUID           `json:"organization_id"`
	EndpointID        pgtype.UUID           `json:"endpoint_id"`
	OutboxID          pgtype.UUID           `json:"outbox_id"`
	EventType         NotificationEventType `json:"event_type"`
	EntityType        string                `json:"entity_type"`
	EntityID          pgtype.UUID           `json:"entity_id"`
	Payload           []byte                `json:"payload"`
	AttemptCount      int32                 `json:"attempt_count"`
	LastAttemptedAt   pgtype.Timestamptz    `json:"last_attempted_at"`
	LeaseExpiresAt    pgtype.Timestamptz    `json:"lease_expires_at"`
	SentAt            pgtype.Timestamptz    `json:"sent_at"`
	FailedPermanently bool                  `json:"failed_permanently"`
	CreatedAt         pgtype.Timestamptz    `json:"created_at"`
}

// Registered webhook endpoints per organization. SSRF-safe: URL is validated at registration time and re-validated at delivery.
type WebhookEndpoint struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Url            string      `json:"url"`
	// AES-256-GCM encrypted webhook secret (nonce prepended). Raw secret is returned once on creation, stored encrypted, never exposed again.
	SecretCiphertext []byte             `json:"secret_ciphertext"`
	Description      *string            `json:"description"`
	Active           bool               `json:"active"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}
