// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationsByUser = `-- name: CountNotificationsByUser :one
SELECT COUNT(*)
FROM   notifications
WHERE  organization_id = $1
  AND  user_id         = $2
  AND  deleted_at      IS NULL
`

type CountNotificationsByUserParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

// Count matching the same filters as ListNotificationsByUser.
func (q *Queries) CountNotificationsByUser(ctx context.Context, arg CountNotificationsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByUser, arg.OrganizationID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :exec

INSERT INTO notifications (
    organization_id,
    user_id,
    outbox_id,
    channel,
    event_type,
    entity_type,
    entity_id,
    payload,
    sent_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateNotificationParams struct {
	OrganizationID pgtype.UUID           `json:"organization_id"`
	UserID         pgtype.UUID           `json:"user_id"`
	OutboxID       pgtype.UUID           `json:"outbox_id"`
	Channel        NotificationChannel   `json:"channel"`
	EventType      NotificationEventType `json:"event_type"`
	EntityType     string                `json:"entity_type"`
	EntityID       pgtype.UUID           `json:"entity_id"`
	Payload        []byte                `json:"payload"`
	SentAt         pgtype.Timestamptz    `json:"sent_at"`
}

// =============================================================================
// NOTIFICATION QUERIES (used by the notifications service / handler)
// =============================================================================
// Written ONLY by DrainOutbox. ON CONFLICT DO NOTHING is applied at the
// application layer to make drain retries idempotent.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.Exec(ctx, createNotification,
		arg.OrganizationID,
		arg.UserID,
		arg.OutboxID,
		arg.Channel,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.Payload,
		arg.SentAt,
	)
	return err
}

const createNotificationOutboxEntry = `-- name: CreateNotificationOutboxEntry :one



INSERT INTO notification_outbox (
    organization_id,
    event_type,
    actor_id,
    entity_type,
    entity_id,
    payload
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, event_type, actor_id, entity_type, entity_id, payload, processed_at, created_at
`

type CreateNotificationOutboxEntryParams struct {
	OrganizationID pgtype.UUID           `json:"organization_id"`
	EventType      NotificationEventType `json:"event_type"`
	ActorID        pgtype.UUID           `json:"actor_id"`
	EntityType     string                `json:"entity_type"`
	EntityID       pgtype.UUID           `json:"entity_id"`
	Payload        []byte                `json:"payload"`
}

// Notifications queries
// All notification and preference queries are scoped by organization_id AND user_id.
// Outbox queries are used only by DrainOutbox and domain-transaction trigger writes.
// =============================================================================
// OUTBOX QUERIES (used by domain repositories and DrainOutbox)
// =============================================================================
// Written inside domain transactions. actor_id may be NULL for system events.
func (q *Queries) CreateNotificationOutboxEntry(ctx context.Context, arg CreateNotificationOutboxEntryParams) (NotificationOutbox, error) {
	row := q.db.QueryRow(ctx, createNotificationOutboxEntry,
		arg.OrganizationID,
		arg.EventType,
		arg.ActorID,
		arg.EntityType,
		arg.EntityID,
		arg.Payload,
	)
	var i NotificationOutbox
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EventType,
		&i.ActorID,
		&i.EntityType,
		&i.EntityID,
		&i.Payload,
		&i.ProcessedAt,
		&i.CreatedAt,
	)
	return i, err
}

const drainOutboxEntries = `-- name: DrainOutboxEntries :many
SELECT id, organization_id, event_type, actor_id, entity_type, entity_id, payload, processed_at, created_at
FROM   notification_outbox
WHERE  organization_id = $1
  AND  processed_at    IS NULL
ORDER  BY created_at ASC
LIMIT  100
FOR    UPDATE SKIP LOCKED
`

// Claims unprocessed outbox entries for a specific organization using
// FOR UPDATE SKIP LOCKED so concurrent drain calls do not double-process.
// Limited to 100 per call to bound transaction size.
func (q *Queries) DrainOutboxEntries(ctx context.Context, organizationID pgtype.UUID) ([]NotificationOutbox, error) {
	rows, err := q.db.Query(ctx, drainOutboxEntries, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationOutbox{}
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EventType,
			&i.ActorID,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.ProcessedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, organization_id, user_id, outbox_id, channel, event_type, entity_type, entity_id, payload, read_at, sent_at, deleted_at, created_at
FROM   notifications
WHERE  id              = $1
  AND  organization_id = $2
  AND  user_id         = $3
  AND  deleted_at      IS NULL
LIMIT  1
`

type GetNotificationByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

// Fetches a single notification scoped by org and user.
// deleted_at IS NULL: soft-deleted notifications are not visible.
func (q *Queries) GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, arg.ID, arg.OrganizationID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.OutboxID,
		&i.Channel,
		&i.EventType,
		&i.EntityType,
		&i.EntityID,
		&i.Payload,
		&i.ReadAt,
		&i.SentAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationPreferencesForEvent = `-- name: GetNotificationPreferencesForEvent :many
SELECT user_id, enabled
FROM   notification_preferences
WHERE  organization_id = $1
  AND  event_type      = $2
  AND  channel         = $3
`

type GetNotificationPreferencesForEventParams struct {
	OrganizationID pgtype.UUID           `json:"organization_id"`
	EventType      NotificationEventType `json:"event_type"`
	Channel        NotificationChannel   `json:"channel"`
}

type GetNotificationPreferencesForEventRow struct {
	UserID  pgtype.UUID `json:"user_id"`
	Enabled bool        `json:"enabled"`
}

// Batch-loads all preference rows for a given (organization_id, event_type, channel).
// Used by DrainOutbox to resolve preferences in memory rather than with per-user
// round-trips: one query per unique (event_type, channel) pair across all pending
// entries, replacing the O(entries × users) pattern with O(unique_pairs).
// A user not present in the result set has no stored preference and is treated
// as enabled = TRUE (the default opt-out model).
func (q *Queries) GetNotificationPreferencesForEvent(ctx context.Context, arg GetNotificationPreferencesForEventParams) ([]GetNotificationPreferencesForEventRow, error) {
	rows, err := q.db.Query(ctx, getNotificationPreferencesForEvent, arg.OrganizationID, arg.EventType, arg.Channel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNotificationPreferencesForEventRow{}
	for rows.Next() {
		var i GetNotificationPreferencesForEventRow
		if err := rows.Scan(&i.UserID, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrgMembersForNotification = `-- name: GetOrgMembersForNotification :many
SELECT DISTINCT uor.user_id
FROM   user_organization_roles uor
WHERE  uor.organization_id = $1
  AND  (uor.expires_at IS NULL OR uor.expires_at > NOW())
`

// Returns distinct user IDs for all non-expired role holders in an org.
// Used by DrainOutbox to determine the fan-out recipient set.
// Platform admins (organization_id IS NULL) are excluded: they are not
// members of a specific org.
func (q *Queries) GetOrgMembersForNotification(ctx context.Context, organizationID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getOrgMembersForNotification, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPreference = `-- name: GetUserPreference :one
SELECT id, organization_id, user_id, event_type, channel, enabled, created_at, updated_at
FROM   notification_preferences
WHERE  organization_id = $1
  AND  user_id         = $2
  AND  event_type      = $3
  AND  channel         = $4
LIMIT  1
`

type GetUserPreferenceParams struct {
	OrganizationID pgtype.UUID           `json:"organization_id"`
	UserID         pgtype.UUID           `json:"user_id"`
	EventType      NotificationEventType `json:"event_type"`
	Channel        NotificationChannel   `json:"channel"`
}

// Fetches a single preference row. Returns ErrNoRows when no preference is set
// (application treats missing row as enabled = TRUE).
func (q *Queries) GetUserPreference(ctx context.Context, arg GetUserPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, getUserPreference,
		arg.OrganizationID,
		arg.UserID,
		arg.EventType,
		arg.Channel,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.EventType,
		&i.Channel,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :many

SELECT id, organization_id, user_id, event_type, channel, enabled, created_at, updated_at
FROM   notification_preferences
WHERE  organization_id = $1
  AND  user_id         = $2
ORDER  BY event_type, channel
`

type GetUserPreferencesParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

// =============================================================================
// PREFERENCE QUERIES (used by the notifications service / handler)
// =============================================================================
// Returns all preferences for a user within an org.
func (q *Queries) GetUserPreferences(ctx context.Context, arg GetUserPreferencesParams) ([]NotificationPreference, error) {
	rows, err := q.db.Query(ctx, getUserPreferences, arg.OrganizationID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationPreference{}
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.EventType,
			&i.Channel,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, organization_id, user_id, outbox_id, channel, event_type, entity_type, entity_id, payload, read_at, sent_at, deleted_at, created_at
FROM   notifications
WHERE  organization_id = $1
  AND  user_id         = $2
  AND  deleted_at      IS NULL
ORDER  BY created_at DESC
LIMIT  $4
OFFSET $3
`

type ListNotificationsByUserParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
	PageOffset     int32       `json:"page_offset"`
	PageLimit      int32       `json:"page_limit"`
}

// Paginated list of undeleted notifications for a user within an org,
// newest first.
func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser,
		arg.OrganizationID,
		arg.UserID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.OutboxID,
			&i.Channel,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.ReadAt,
			&i.SentAt,
			&i.DeletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET    read_at = NOW()
WHERE  organization_id = $1
  AND  user_id         = $2
  AND  deleted_at      IS NULL
  AND  read_at         IS NULL
`

type MarkAllNotificationsReadParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

// Marks all unread, undeleted notifications as read for a user within an org.
func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, arg.OrganizationID, arg.UserID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET    read_at = NOW()
WHERE  id              = $1
  AND  organization_id = $2
  AND  user_id         = $3
  AND  deleted_at      IS NULL
  AND  read_at         IS NULL
RETURNING id, organization_id, user_id, outbox_id, channel, event_type, entity_type, entity_id, payload, read_at, sent_at, deleted_at, created_at
`

type MarkNotificationReadParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

// Sets read_at to NOW() for a specific notification owned by the user.
// Returns the updated row so the handler can return the new state.
func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.OrganizationID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.OutboxID,
		&i.Channel,
		&i.EventType,
		&i.EntityType,
		&i.EntityID,
		&i.Payload,
		&i.ReadAt,
		&i.SentAt,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markOutboxEntryProcessed = `-- name: MarkOutboxEntryProcessed :exec
UPDATE notification_outbox
SET    processed_at = NOW()
WHERE  id = $1
`

// Called by DrainOutbox after all notifications for this entry have been inserted.
func (q *Queries) MarkOutboxEntryProcessed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOutboxEntryProcessed, id)
	return err
}

const softDeleteNotification = `-- name: SoftDeleteNotification :execrows
UPDATE notifications
SET    deleted_at = NOW()
WHERE  id              = $1
  AND  organization_id = $2
  AND  user_id         = $3
  AND  deleted_at      IS NULL
`

type SoftDeleteNotificationParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

// Soft-deletes a notification by setting deleted_at.
// Returns the number of rows affected (0 = not found / already deleted).
func (q *Queries) SoftDeleteNotification(ctx context.Context, arg SoftDeleteNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteNotification, arg.ID, arg.OrganizationID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :one
INSERT INTO notification_preferences (
    organization_id,
    user_id,
    event_type,
    channel,
    enabled
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (organization_id, user_id, event_type, channel)
DO UPDATE SET
    enabled    = EXCLUDED.enabled,
    updated_at = NOW()
RETURNING id, organization_id, user_id, event_type, channel, enabled, created_at, updated_at
`

type UpsertNotificationPreferenceParams struct {
	OrganizationID pgtype.UUID           `json:"organization_id"`
	UserID         pgtype.UUID           `json:"user_id"`
	EventType      NotificationEventType `json:"event_type"`
	Channel        NotificationChannel   `json:"channel"`
	Enabled        bool                  `json:"enabled"`
}

// Creates or updates a preference (last-writer-wins).
func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreference,
		arg.OrganizationID,
		arg.UserID,
		arg.EventType,
		arg.Channel,
		arg.Enabled,
	)
	var i NotificationPreference
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.EventType,
		&i.Channel,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
