// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organizations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrganizationByID = `-- name: GetOrganizationByID :one

SELECT id, name, slug, description, type, status, logo_url, website, email, phone, country, city, settings, created_at, updated_at
FROM   organizations
WHERE  id = $1
LIMIT  1
`

// Organizations queries
// All writes go through the service layer; only reads are generated here.
func (q *Queries) GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.LogoUrl,
		&i.Website,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.City,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, name, slug, description, type, status, logo_url, website, email, phone, country, city, settings, created_at, updated_at
FROM   organizations
WHERE  slug = $1
LIMIT  1
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Type,
		&i.Status,
		&i.LogoUrl,
		&i.Website,
		&i.Email,
		&i.Phone,
		&i.Country,
		&i.City,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, name, slug, description, type, status, logo_url, website, email, phone, country, city, settings, created_at, updated_at
FROM   organizations
ORDER  BY created_at DESC
`

func (q *Queries) ListOrganizations(ctx context.Context) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.LogoUrl,
			&i.Website,
			&i.Email,
			&i.Phone,
			&i.Country,
			&i.City,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
