// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one

INSERT INTO password_reset_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Password reset token queries
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens
WHERE  expires_at <= $1
`

// Removes tokens past their expiry. Called by the background cleanup scheduler.
// Both unused-expired and used tokens are eligible for deletion.
func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens, expiresAt)
	return err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM   password_reset_tokens
WHERE  token_hash = $1
LIMIT  1
`

// Non-locking fetch used as a pre-flight read in ResetPasswordTransaction.
// Returns the row regardless of used/expired state so the caller can obtain
// the user_id before acquiring the deterministic per-user lock set.
func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetTokenByHashForUpdate = `-- name: GetPasswordResetTokenByHashForUpdate :one
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM   password_reset_tokens
WHERE  token_hash = $1
FOR UPDATE
`

// Acquires a row-level exclusive lock on the token row.
// Used by ResetPasswordTransaction to serialize concurrent consumption:
// the second concurrent call blocks until the first commits, then reads
// used_at IS NOT NULL and returns ErrResetTokenUsed.
func (q *Queries) GetPasswordResetTokenByHashForUpdate(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHashForUpdate, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const lockUserPasswordResetTokens = `-- name: LockUserPasswordResetTokens :many
SELECT id, user_id, token_hash, expires_at, used_at, created_at
FROM   password_reset_tokens
WHERE  user_id  = $1
  AND  used_at  IS NULL
ORDER BY id
FOR UPDATE
`

// Acquires exclusive row locks on all outstanding (unused) reset tokens for
// a user in deterministic ascending-id order. Called inside
// ResetPasswordTransaction before any UPDATE, ensuring that two concurrent
// reset attempts each presenting a different token for the same user always
// compete for the same lock set in the same order and therefore cannot
// deadlock.
func (q *Queries) LockUserPasswordResetTokens(ctx context.Context, userID pgtype.UUID) ([]PasswordResetToken, error) {
	rows, err := q.db.Query(ctx, lockUserPasswordResetTokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PasswordResetToken{}
	for rows.Next() {
		var i PasswordResetToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const useAllUserPasswordResetTokens = `-- name: UseAllUserPasswordResetTokens :exec
UPDATE password_reset_tokens
SET    used_at = NOW()
WHERE  user_id = $1
  AND  used_at IS NULL
`

// Invalidates all outstanding (unused) reset tokens for a user after a
// successful reset. Prevents stale tokens issued before the reset from being
// used to change the password again.
func (q *Queries) UseAllUserPasswordResetTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, useAllUserPasswordResetTokens, userID)
	return err
}

const usePasswordResetToken = `-- name: UsePasswordResetToken :exec
UPDATE password_reset_tokens
SET    used_at = NOW()
WHERE  id      = $1
  AND  used_at IS NULL
`

// Marks a specific token as consumed. The AND used_at IS NULL guard prevents
// a concurrent double-use from silently succeeding.
func (q *Queries) UsePasswordResetToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, usePasswordResetToken, id)
	return err
}
