// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: players.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlayerByID = `-- name: GetPlayerByID :one

SELECT id, organization_id, user_id, display_name, jersey_number, position, height_cm, weight_kg, dominant_hand, nationality, date_of_birth, status, bio, metadata, created_at, updated_at
FROM   players
WHERE  id              = $1
  AND  organization_id = $2
LIMIT  1
`

type GetPlayerByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Players queries
// organization_id is always required to enforce tenant isolation.
func (q *Queries) GetPlayerByID(ctx context.Context, arg GetPlayerByIDParams) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, arg.ID, arg.OrganizationID)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.DisplayName,
		&i.JerseyNumber,
		&i.Position,
		&i.HeightCm,
		&i.WeightKg,
		&i.DominantHand,
		&i.Nationality,
		&i.DateOfBirth,
		&i.Status,
		&i.Bio,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlayersByOrganization = `-- name: ListPlayersByOrganization :many
SELECT id, organization_id, user_id, display_name, jersey_number, position, height_cm, weight_kg, dominant_hand, nationality, date_of_birth, status, bio, metadata, created_at, updated_at
FROM   players
WHERE  organization_id = $1
ORDER  BY display_name ASC
`

func (q *Queries) ListPlayersByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]Player, error) {
	rows, err := q.db.Query(ctx, listPlayersByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Player{}
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.DisplayName,
			&i.JerseyNumber,
			&i.Position,
			&i.HeightCm,
			&i.WeightKg,
			&i.DominantHand,
			&i.Nationality,
			&i.DateOfBirth,
			&i.Status,
			&i.Bio,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
