// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPublicMatch = `-- name: GetPublicMatch :one
SELECT id,
       round_number,
       round_name,
       match_number,
       group_label,
       home_team_id,
       away_team_id,
       home_player_id,
       away_player_id,
       scheduled_at,
       started_at,
       ended_at,
       venue,
       status,
       home_score,
       away_score,
       is_walkover,
       winner_team_id,
       winner_player_id
FROM   matches
WHERE  id              = $1
  AND  tournament_id   = $2
  AND  organization_id = $3
LIMIT  1
`

type GetPublicMatchParams struct {
	ID             pgtype.UUID `json:"id"`
	TournamentID   pgtype.UUID `json:"tournament_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetPublicMatchRow struct {
	ID             pgtype.UUID        `json:"id"`
	RoundNumber    *int16             `json:"round_number"`
	RoundName      *string            `json:"round_name"`
	MatchNumber    *int16             `json:"match_number"`
	GroupLabel     *string            `json:"group_label"`
	HomeTeamID     pgtype.UUID        `json:"home_team_id"`
	AwayTeamID     pgtype.UUID        `json:"away_team_id"`
	HomePlayerID   pgtype.UUID        `json:"home_player_id"`
	AwayPlayerID   pgtype.UUID        `json:"away_player_id"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
	Venue          *string            `json:"venue"`
	Status         MatchStatus        `json:"status"`
	HomeScore      int32              `json:"home_score"`
	AwayScore      int32              `json:"away_score"`
	IsWalkover     bool               `json:"is_walkover"`
	WinnerTeamID   pgtype.UUID        `json:"winner_team_id"`
	WinnerPlayerID pgtype.UUID        `json:"winner_player_id"`
}

// A single whitelisted match within a publicly-resolved tournament.
func (q *Queries) GetPublicMatch(ctx context.Context, arg GetPublicMatchParams) (GetPublicMatchRow, error) {
	row := q.db.QueryRow(ctx, getPublicMatch, arg.ID, arg.TournamentID, arg.OrganizationID)
	var i GetPublicMatchRow
	err := row.Scan(
		&i.ID,
		&i.RoundNumber,
		&i.RoundName,
		&i.MatchNumber,
		&i.GroupLabel,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomePlayerID,
		&i.AwayPlayerID,
		&i.ScheduledAt,
		&i.StartedAt,
		&i.EndedAt,
		&i.Venue,
		&i.Status,
		&i.HomeScore,
		&i.AwayScore,
		&i.IsWalkover,
		&i.WinnerTeamID,
		&i.WinnerPlayerID,
	)
	return i, err
}

const getPublicTournament = `-- name: GetPublicTournament :one

SELECT t.id,
       t.name,
       t.slug,
       t.sport,
       t.format,
       t.participant_type,
       t.status,
       t.visibility,
       t.banner_url,
       t.description,
       t.prize_pool,
       t.currency,
       t.max_participants,
       t.registration_opens_at,
       t.registration_closes_at,
       t.starts_at,
       t.ends_at,
       t.venue,
       t.city,
       t.country,
       t.rules,
       t.created_at,
       t.organization_id,
       o.name AS organization_name,
       o.slug AS organization_slug
FROM   tournaments t
JOIN   organizations o ON o.id = t.organization_id
WHERE  o.slug       = $1
  AND  t.slug       = $2
  AND  t.status    <> 'draft'
  AND  t.visibility IN ('unlisted', 'public')
  AND  o.status     = 'active'
LIMIT  1
`

type GetPublicTournamentParams struct {
	Slug   string `json:"slug"`
	Slug_2 string `json:"slug_2"`
}

type GetPublicTournamentRow struct {
	ID                   pgtype.UUID          `json:"id"`
	Name                 string               `json:"name"`
	Slug                 string               `json:"slug"`
	Sport                string               `json:"sport"`
	Format               TournamentFormat     `json:"format"`
	ParticipantType      ParticipantType      `json:"participant_type"`
	Status               TournamentStatus     `json:"status"`
	Visibility           TournamentVisibility `json:"visibility"`
	BannerUrl            *string              `json:"banner_url"`
	Description          *string              `json:"description"`
	PrizePool            pgtype.Numeric       `json:"prize_pool"`
	Currency             string               `json:"currency"`
	MaxParticipants      *int16               `json:"max_participants"`
	RegistrationOpensAt  pgtype.Timestamptz   `json:"registration_opens_at"`
	RegistrationClosesAt pgtype.Timestamptz   `json:"registration_closes_at"`
	StartsAt             pgtype.Timestamptz   `json:"starts_at"`
	EndsAt               pgtype.Timestamptz   `json:"ends_at"`
	Venue                *string              `json:"venue"`
	City                 *string              `json:"city"`
	Country              *string              `json:"country"`
	Rules                *string              `json:"rules"`
	CreatedAt            pgtype.Timestamptz   `json:"created_at"`
	OrganizationID       pgtype.UUID          `json:"organization_id"`
	OrganizationName     string               `json:"organization_name"`
	OrganizationSlug     string               `json:"organization_slug"`
}

// Public (unauthenticated) read queries — PRI-1.
//
// These are the ONLY queries the anonymous public path may use. Authorization is
// expressed entirely through SQL visibility constraints — never a principal
// check. Every query selects an explicit whitelist of columns: NO "SELECT *",
// NO settings/audit/PII/internal-notes columns are ever exposed.
//
// Public eligibility gate (repeated in each entry query):
//
//	tournament.status <> 'draft'
//	AND tournament.visibility IN ('unlisted','public')
//	AND owning organization.status = 'active'
//
// A row failing the gate is simply not returned → the service maps the empty
// result to 404 (never 403), so private/draft tournaments cannot be probed for
// existence.
// Resolves a publicly-eligible tournament by (org slug, tournament slug).
// Returns only whitelisted, shareable fields plus org branding (name/slug).
// Note the explicit absence of settings, created_by, and updated_by.
func (q *Queries) GetPublicTournament(ctx context.Context, arg GetPublicTournamentParams) (GetPublicTournamentRow, error) {
	row := q.db.QueryRow(ctx, getPublicTournament, arg.Slug, arg.Slug_2)
	var i GetPublicTournamentRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Sport,
		&i.Format,
		&i.ParticipantType,
		&i.Status,
		&i.Visibility,
		&i.BannerUrl,
		&i.Description,
		&i.PrizePool,
		&i.Currency,
		&i.MaxParticipants,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.StartsAt,
		&i.EndsAt,
		&i.Venue,
		&i.City,
		&i.Country,
		&i.Rules,
		&i.CreatedAt,
		&i.OrganizationID,
		&i.OrganizationName,
		&i.OrganizationSlug,
	)
	return i, err
}

const listPublicMatchEvents = `-- name: ListPublicMatchEvents :many
SELECT me.id,
       me.sequence_number,
       me.event_type,
       me.period,
       me.clock_seconds,
       me.team_id,
       me.player_id,
       me.recorded_at
FROM   match_events me
WHERE  me.match_id        = $1
  AND  me.organization_id = $2
  AND  me.event_type     <> 'score_correction'
  AND  me.id NOT IN (
           SELECT c.cancels_event_id
           FROM   match_events c
           WHERE  c.match_id         = $1
             AND  c.cancels_event_id IS NOT NULL
       )
ORDER  BY me.sequence_number ASC
LIMIT  500
`

type ListPublicMatchEventsParams struct {
	MatchID        pgtype.UUID `json:"match_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListPublicMatchEventsRow struct {
	ID             pgtype.UUID        `json:"id"`
	SequenceNumber int64              `json:"sequence_number"`
	EventType      MatchEventType     `json:"event_type"`
	Period         *int16             `json:"period"`
	ClockSeconds   *int32             `json:"clock_seconds"`
	TeamID         pgtype.UUID        `json:"team_id"`
	PlayerID       pgtype.UUID        `json:"player_id"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
}

// Whitelisted, effective (non-cancelled) timeline events for a public match.
// Excludes payload, recorded_by, cancels_event_id. Capped to keep the public
// response bounded.
func (q *Queries) ListPublicMatchEvents(ctx context.Context, arg ListPublicMatchEventsParams) ([]ListPublicMatchEventsRow, error) {
	rows, err := q.db.Query(ctx, listPublicMatchEvents, arg.MatchID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicMatchEventsRow{}
	for rows.Next() {
		var i ListPublicMatchEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.SequenceNumber,
			&i.EventType,
			&i.Period,
			&i.ClockSeconds,
			&i.TeamID,
			&i.PlayerID,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicMatches = `-- name: ListPublicMatches :many
SELECT id,
       round_number,
       round_name,
       match_number,
       group_label,
       home_team_id,
       away_team_id,
       home_player_id,
       away_player_id,
       scheduled_at,
       started_at,
       ended_at,
       venue,
       status,
       home_score,
       away_score,
       is_walkover,
       winner_team_id,
       winner_player_id,
       next_match_id,
       next_match_slot
FROM   matches
WHERE  tournament_id   = $1
  AND  organization_id = $2
ORDER  BY round_number ASC NULLS LAST, match_number ASC NULLS LAST
`

type ListPublicMatchesParams struct {
	TournamentID   pgtype.UUID `json:"tournament_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type ListPublicMatchesRow struct {
	ID             pgtype.UUID        `json:"id"`
	RoundNumber    *int16             `json:"round_number"`
	RoundName      *string            `json:"round_name"`
	MatchNumber    *int16             `json:"match_number"`
	GroupLabel     *string            `json:"group_label"`
	HomeTeamID     pgtype.UUID        `json:"home_team_id"`
	AwayTeamID     pgtype.UUID        `json:"away_team_id"`
	HomePlayerID   pgtype.UUID        `json:"home_player_id"`
	AwayPlayerID   pgtype.UUID        `json:"away_player_id"`
	ScheduledAt    pgtype.Timestamptz `json:"scheduled_at"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
	Venue          *string            `json:"venue"`
	Status         MatchStatus        `json:"status"`
	HomeScore      int32              `json:"home_score"`
	AwayScore      int32              `json:"away_score"`
	IsWalkover     bool               `json:"is_walkover"`
	WinnerTeamID   pgtype.UUID        `json:"winner_team_id"`
	WinnerPlayerID pgtype.UUID        `json:"winner_player_id"`
	NextMatchID    pgtype.UUID        `json:"next_match_id"`
	NextMatchSlot  *int16             `json:"next_match_slot"`
}

// Whitelisted match rows for a (publicly-resolved) tournament. Excludes notes,
// metadata, created_by/recorded_by. Participant/winner names are resolved by the
// service via the batch name queries — ids here are non-secret render handles.
func (q *Queries) ListPublicMatches(ctx context.Context, arg ListPublicMatchesParams) ([]ListPublicMatchesRow, error) {
	rows, err := q.db.Query(ctx, listPublicMatches, arg.TournamentID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublicMatchesRow{}
	for rows.Next() {
		var i ListPublicMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoundNumber,
			&i.RoundName,
			&i.MatchNumber,
			&i.GroupLabel,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomePlayerID,
			&i.AwayPlayerID,
			&i.ScheduledAt,
			&i.StartedAt,
			&i.EndedAt,
			&i.Venue,
			&i.Status,
			&i.HomeScore,
			&i.AwayScore,
			&i.IsWalkover,
			&i.WinnerTeamID,
			&i.WinnerPlayerID,
			&i.NextMatchID,
			&i.NextMatchSlot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
