// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rankings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPlayerRankings = `-- name: CountPlayerRankings :one
SELECT COUNT(DISTINCT pts.player_id)
FROM   player_tournament_stats pts
JOIN   players p ON p.id = pts.player_id
WHERE  pts.organization_id = $1
  AND  p.status = 'active'
`

// Returns total number of active players with at least one completed tournament
// in the organization. Used for pagination metadata.
func (q *Queries) CountPlayerRankings(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPlayerRankings, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamRankings = `-- name: CountTeamRankings :one
SELECT COUNT(DISTINCT tts.team_id)
FROM   team_tournament_stats tts
JOIN   teams t ON t.id = tts.team_id
WHERE  tts.organization_id = $1
  AND  t.status = 'active'
`

func (q *Queries) CountTeamRankings(ctx context.Context, organizationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamRankings, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listPlayerRankings = `-- name: ListPlayerRankings :many
WITH aggregated AS (
    SELECT
        p.id                                                              AS player_id,
        p.display_name                                                    AS display_name,
        COUNT(DISTINCT pts.tournament_id)                                 AS tournaments_played,
        SUM(CASE WHEN pts.position = 1  THEN 1 ELSE 0 END)               AS tournaments_won,
        SUM(CASE WHEN pts.position <= 3 THEN 1 ELSE 0 END)               AS podium_finishes,
        SUM(pts.matches_played)                                           AS total_matches,
        SUM(pts.matches_won)                                              AS total_wins,
        SUM(pts.matches_drawn)                                            AS total_draws,
        SUM(pts.matches_lost)                                             AS total_losses,
        SUM(pts.points)                                                   AS total_points,
        SUM(pts.score_for)                                                AS score_for,
        SUM(pts.score_against)                                            AS score_against
    FROM   player_tournament_stats pts
    JOIN   players p ON p.id = pts.player_id
    WHERE  pts.organization_id = $1
      AND  p.status = 'active'
    GROUP  BY p.id, p.display_name
)
SELECT
    RANK() OVER (
        ORDER BY
            tournaments_won  DESC,
            podium_finishes  DESC,
            total_points     DESC,
            total_wins       DESC,
            total_matches    DESC
    )::int                   AS rank,
    player_id,
    display_name,
    tournaments_played::int  AS tournaments_played,
    tournaments_won::int     AS tournaments_won,
    podium_finishes::int     AS podium_finishes,
    total_matches::int       AS total_matches,
    total_wins::int          AS total_wins,
    total_draws::int         AS total_draws,
    total_losses::int        AS total_losses,
    total_points::int        AS total_points,
    score_for::int           AS score_for,
    score_against::int       AS score_against
FROM   aggregated
ORDER  BY rank ASC, player_id ASC
LIMIT  $2
OFFSET $3
`

type ListPlayerRankingsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

type ListPlayerRankingsRow struct {
	Rank              int32       `json:"rank"`
	PlayerID          pgtype.UUID `json:"player_id"`
	DisplayName       string      `json:"display_name"`
	TournamentsPlayed int32       `json:"tournaments_played"`
	TournamentsWon    int32       `json:"tournaments_won"`
	PodiumFinishes    int32       `json:"podium_finishes"`
	TotalMatches      int32       `json:"total_matches"`
	TotalWins         int32       `json:"total_wins"`
	TotalDraws        int32       `json:"total_draws"`
	TotalLosses       int32       `json:"total_losses"`
	TotalPoints       int32       `json:"total_points"`
	ScoreFor          int32       `json:"score_for"`
	ScoreAgainst      int32       `json:"score_against"`
}

// Returns all-time player rankings for an organization, ordered by the
// five-level tiebreak chain. Only active players are included.
// win_rate is computed in the service layer to avoid float precision issues.
func (q *Queries) ListPlayerRankings(ctx context.Context, arg ListPlayerRankingsParams) ([]ListPlayerRankingsRow, error) {
	rows, err := q.db.Query(ctx, listPlayerRankings, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerRankingsRow{}
	for rows.Next() {
		var i ListPlayerRankingsRow
		if err := rows.Scan(
			&i.Rank,
			&i.PlayerID,
			&i.DisplayName,
			&i.TournamentsPlayed,
			&i.TournamentsWon,
			&i.PodiumFinishes,
			&i.TotalMatches,
			&i.TotalWins,
			&i.TotalDraws,
			&i.TotalLosses,
			&i.TotalPoints,
			&i.ScoreFor,
			&i.ScoreAgainst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamRankings = `-- name: ListTeamRankings :many
WITH aggregated AS (
    SELECT
        t.id                                                              AS team_id,
        t.name                                                            AS team_name,
        COUNT(DISTINCT tts.tournament_id)                                 AS tournaments_played,
        SUM(CASE WHEN tts.position = 1  THEN 1 ELSE 0 END)               AS tournaments_won,
        SUM(CASE WHEN tts.position <= 3 THEN 1 ELSE 0 END)               AS podium_finishes,
        SUM(tts.matches_played)                                           AS total_matches,
        SUM(tts.matches_won)                                              AS total_wins,
        SUM(tts.matches_drawn)                                            AS total_draws,
        SUM(tts.matches_lost)                                             AS total_losses,
        SUM(tts.points)                                                   AS total_points,
        SUM(tts.score_for)                                                AS score_for,
        SUM(tts.score_against)                                            AS score_against
    FROM   team_tournament_stats tts
    JOIN   teams t ON t.id = tts.team_id
    WHERE  tts.organization_id = $1
      AND  t.status = 'active'
    GROUP  BY t.id, t.name
)
SELECT
    RANK() OVER (
        ORDER BY
            tournaments_won  DESC,
            podium_finishes  DESC,
            total_points     DESC,
            total_wins       DESC,
            total_matches    DESC
    )::int                   AS rank,
    team_id,
    team_name,
    tournaments_played::int  AS tournaments_played,
    tournaments_won::int     AS tournaments_won,
    podium_finishes::int     AS podium_finishes,
    total_matches::int       AS total_matches,
    total_wins::int          AS total_wins,
    total_draws::int         AS total_draws,
    total_losses::int        AS total_losses,
    total_points::int        AS total_points,
    score_for::int           AS score_for,
    score_against::int       AS score_against
FROM   aggregated
ORDER  BY rank ASC, team_id ASC
LIMIT  $2
OFFSET $3
`

type ListTeamRankingsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Limit          int32       `json:"limit"`
	Offset         int32       `json:"offset"`
}

type ListTeamRankingsRow struct {
	Rank              int32       `json:"rank"`
	TeamID            pgtype.UUID `json:"team_id"`
	TeamName          string      `json:"team_name"`
	TournamentsPlayed int32       `json:"tournaments_played"`
	TournamentsWon    int32       `json:"tournaments_won"`
	PodiumFinishes    int32       `json:"podium_finishes"`
	TotalMatches      int32       `json:"total_matches"`
	TotalWins         int32       `json:"total_wins"`
	TotalDraws        int32       `json:"total_draws"`
	TotalLosses       int32       `json:"total_losses"`
	TotalPoints       int32       `json:"total_points"`
	ScoreFor          int32       `json:"score_for"`
	ScoreAgainst      int32       `json:"score_against"`
}

func (q *Queries) ListTeamRankings(ctx context.Context, arg ListTeamRankingsParams) ([]ListTeamRankingsRow, error) {
	rows, err := q.db.Query(ctx, listTeamRankings, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamRankingsRow{}
	for rows.Next() {
		var i ListTeamRankingsRow
		if err := rows.Scan(
			&i.Rank,
			&i.TeamID,
			&i.TeamName,
			&i.TournamentsPlayed,
			&i.TournamentsWon,
			&i.PodiumFinishes,
			&i.TotalMatches,
			&i.TotalWins,
			&i.TotalDraws,
			&i.TotalLosses,
			&i.TotalPoints,
			&i.ScoreFor,
			&i.ScoreAgainst,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlayerTournamentStats = `-- name: UpsertPlayerTournamentStats :exec

INSERT INTO player_tournament_stats (
    player_id, tournament_id, organization_id,
    position, matches_played, matches_won, matches_drawn, matches_lost,
    points, score_for, score_against, snapshotted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW()
)
ON CONFLICT (player_id, tournament_id) DO UPDATE SET
    organization_id = EXCLUDED.organization_id,
    position        = EXCLUDED.position,
    matches_played  = EXCLUDED.matches_played,
    matches_won     = EXCLUDED.matches_won,
    matches_drawn   = EXCLUDED.matches_drawn,
    matches_lost    = EXCLUDED.matches_lost,
    points          = EXCLUDED.points,
    score_for       = EXCLUDED.score_for,
    score_against   = EXCLUDED.score_against,
    snapshotted_at  = NOW()
`

type UpsertPlayerTournamentStatsParams struct {
	PlayerID       pgtype.UUID `json:"player_id"`
	TournamentID   pgtype.UUID `json:"tournament_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Position       int32       `json:"position"`
	MatchesPlayed  int32       `json:"matches_played"`
	MatchesWon     int32       `json:"matches_won"`
	MatchesDrawn   int32       `json:"matches_drawn"`
	MatchesLost    int32       `json:"matches_lost"`
	Points         int32       `json:"points"`
	ScoreFor       int32       `json:"score_for"`
	ScoreAgainst   int32       `json:"score_against"`
}

// Rankings queries
// Upserts are called at tournament completion (idempotent on retry).
// List queries aggregate per-tournament rows and apply RANK() window function.
// Idempotent upsert: re-running on retry produces the same result.
func (q *Queries) UpsertPlayerTournamentStats(ctx context.Context, arg UpsertPlayerTournamentStatsParams) error {
	_, err := q.db.Exec(ctx, upsertPlayerTournamentStats,
		arg.PlayerID,
		arg.TournamentID,
		arg.OrganizationID,
		arg.Position,
		arg.MatchesPlayed,
		arg.MatchesWon,
		arg.MatchesDrawn,
		arg.MatchesLost,
		arg.Points,
		arg.ScoreFor,
		arg.ScoreAgainst,
	)
	return err
}

const upsertTeamTournamentStats = `-- name: UpsertTeamTournamentStats :exec
INSERT INTO team_tournament_stats (
    team_id, tournament_id, organization_id,
    position, matches_played, matches_won, matches_drawn, matches_lost,
    points, score_for, score_against, snapshotted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, NOW()
)
ON CONFLICT (team_id, tournament_id) DO UPDATE SET
    organization_id = EXCLUDED.organization_id,
    position        = EXCLUDED.position,
    matches_played  = EXCLUDED.matches_played,
    matches_won     = EXCLUDED.matches_won,
    matches_drawn   = EXCLUDED.matches_drawn,
    matches_lost    = EXCLUDED.matches_lost,
    points          = EXCLUDED.points,
    score_for       = EXCLUDED.score_for,
    score_against   = EXCLUDED.score_against,
    snapshotted_at  = NOW()
`

type UpsertTeamTournamentStatsParams struct {
	TeamID         pgtype.UUID `json:"team_id"`
	TournamentID   pgtype.UUID `json:"tournament_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Position       int32       `json:"position"`
	MatchesPlayed  int32       `json:"matches_played"`
	MatchesWon     int32       `json:"matches_won"`
	MatchesDrawn   int32       `json:"matches_drawn"`
	MatchesLost    int32       `json:"matches_lost"`
	Points         int32       `json:"points"`
	ScoreFor       int32       `json:"score_for"`
	ScoreAgainst   int32       `json:"score_against"`
}

func (q *Queries) UpsertTeamTournamentStats(ctx context.Context, arg UpsertTeamTournamentStatsParams) error {
	_, err := q.db.Exec(ctx, upsertTeamTournamentStats,
		arg.TeamID,
		arg.TournamentID,
		arg.OrganizationID,
		arg.Position,
		arg.MatchesPlayed,
		arg.MatchesWon,
		arg.MatchesDrawn,
		arg.MatchesLost,
		arg.Points,
		arg.ScoreFor,
		arg.ScoreAgainst,
	)
	return err
}
