// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserOrganizations = `-- name: GetUserOrganizations :many
SELECT DISTINCT o.id, o.name, o.slug, o.description, o.type, o.status, o.logo_url, o.website, o.email, o.phone, o.country, o.city, o.settings, o.created_at, o.updated_at
FROM   user_organization_roles uor
JOIN   organizations o ON uor.organization_id = o.id
WHERE  uor.user_id = $1
  AND  uor.organization_id IS NOT NULL
  AND  (uor.expires_at IS NULL OR uor.expires_at > NOW())
ORDER  BY o.name ASC
`

func (q *Queries) GetUserOrganizations(ctx context.Context, userID pgtype.UUID) ([]Organization, error) {
	rows, err := q.db.Query(ctx, getUserOrganizations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Type,
			&i.Status,
			&i.LogoUrl,
			&i.Website,
			&i.Email,
			&i.Phone,
			&i.Country,
			&i.City,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPlatformRoles = `-- name: GetUserPlatformRoles :many
SELECT r.id, r.organization_id, r.name, r.slug, r.description, r.scope, r.is_system, r.created_at, r.updated_at
FROM   user_organization_roles uor
JOIN   roles r ON uor.role_id = r.id
WHERE  uor.user_id = $1
  AND  uor.organization_id IS NULL
  AND  (uor.expires_at IS NULL OR uor.expires_at > NOW())
ORDER  BY r.name ASC
`

func (q *Queries) GetUserPlatformRoles(ctx context.Context, userID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, getUserPlatformRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Scope,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRolesByOrganization = `-- name: GetUserRolesByOrganization :many

SELECT r.id, r.organization_id, r.name, r.slug, r.description, r.scope, r.is_system, r.created_at, r.updated_at
FROM   user_organization_roles uor
JOIN   roles r ON uor.role_id = r.id
WHERE  uor.user_id = $1
  AND  uor.organization_id = $2
  AND  (uor.expires_at IS NULL OR uor.expires_at > NOW())
ORDER  BY r.name ASC
`

type GetUserRolesByOrganizationParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// RBAC queries
// Role and permission lookups for authorization
func (q *Queries) GetUserRolesByOrganization(ctx context.Context, arg GetUserRolesByOrganizationParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, getUserRolesByOrganization, arg.UserID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Scope,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
