// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_memberships.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMembership = `-- name: CreateMembership :one
INSERT INTO team_memberships (
    team_id, player_id, organization_id,
    role, jersey_number, notes
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, team_id, player_id, role, jersey_number, status, joined_at, left_at, notes, created_at, updated_at, organization_id
`

type CreateMembershipParams struct {
	TeamID         pgtype.UUID    `json:"team_id"`
	PlayerID       pgtype.UUID    `json:"player_id"`
	OrganizationID pgtype.UUID    `json:"organization_id"`
	Role           MembershipRole `json:"role"`
	JerseyNumber   *string        `json:"jersey_number"`
	Notes          *string        `json:"notes"`
}

// Inserts a new active membership row. The DB trigger
// trg_team_memberships_org_consistency validates that team_id and player_id
// both belong to organization_id; the service layer validates this first to
// return a meaningful error before hitting the trigger.
func (q *Queries) CreateMembership(ctx context.Context, arg CreateMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, createMembership,
		arg.TeamID,
		arg.PlayerID,
		arg.OrganizationID,
		arg.Role,
		arg.JerseyNumber,
		arg.Notes,
	)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.PlayerID,
		&i.Role,
		&i.JerseyNumber,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getActiveMembershipByPlayer = `-- name: GetActiveMembershipByPlayer :one
SELECT id, team_id, player_id, role, jersey_number, status, joined_at, left_at, notes, created_at, updated_at, organization_id
FROM   team_memberships
WHERE  player_id       = $1
  AND  organization_id = $2
  AND  status          = 'active'
LIMIT  1
`

type GetActiveMembershipByPlayerParams struct {
	PlayerID       pgtype.UUID `json:"player_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Enforces the rule: one active team membership per player per organization.
// Does NOT filter by team_id so that any existing active membership on any
// team within the org is detected before a new one is created.
func (q *Queries) GetActiveMembershipByPlayer(ctx context.Context, arg GetActiveMembershipByPlayerParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, getActiveMembershipByPlayer, arg.PlayerID, arg.OrganizationID)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.PlayerID,
		&i.Role,
		&i.JerseyNumber,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getActiveMembershipByTeamAndPlayer = `-- name: GetActiveMembershipByTeamAndPlayer :one
SELECT id, team_id, player_id, role, jersey_number, status, joined_at, left_at, notes, created_at, updated_at, organization_id
FROM   team_memberships
WHERE  team_id         = $1
  AND  player_id       = $2
  AND  organization_id = $3
  AND  status          = 'active'
LIMIT  1
`

type GetActiveMembershipByTeamAndPlayerParams struct {
	TeamID         pgtype.UUID `json:"team_id"`
	PlayerID       pgtype.UUID `json:"player_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Returns the current active membership for a (team, player) pair.
// Retained for internal use; the primary exclusivity check is
// GetActiveMembershipByPlayer which enforces the org-wide rule.
func (q *Queries) GetActiveMembershipByTeamAndPlayer(ctx context.Context, arg GetActiveMembershipByTeamAndPlayerParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, getActiveMembershipByTeamAndPlayer, arg.TeamID, arg.PlayerID, arg.OrganizationID)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.PlayerID,
		&i.Role,
		&i.JerseyNumber,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const getMembershipByID = `-- name: GetMembershipByID :one

SELECT id, team_id, player_id, role, jersey_number, status, joined_at, left_at, notes, created_at, updated_at, organization_id
FROM   team_memberships
WHERE  id              = $1
  AND  organization_id = $2
LIMIT  1
`

type GetMembershipByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Team membership queries
// organization_id is always required to enforce tenant isolation.
// All three of team_id, player_id, and organization_id must be consistent
// (enforced by both the application service layer and the DB trigger
// trg_team_memberships_org_consistency).
func (q *Queries) GetMembershipByID(ctx context.Context, arg GetMembershipByIDParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipByID, arg.ID, arg.OrganizationID)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.PlayerID,
		&i.Role,
		&i.JerseyNumber,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}

const hasActiveMembersByTeam = `-- name: HasActiveMembersByTeam :one
SELECT EXISTS(
    SELECT 1
    FROM   team_memberships
    WHERE  team_id         = $1
      AND  organization_id = $2
      AND  status          = 'active'
) AS has_members
`

type HasActiveMembersByTeamParams struct {
	TeamID         pgtype.UUID `json:"team_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Returns true if the team has at least one active member.
// Used by tournament registration to reject empty teams.
func (q *Queries) HasActiveMembersByTeam(ctx context.Context, arg HasActiveMembersByTeamParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveMembersByTeam, arg.TeamID, arg.OrganizationID)
	var has_members bool
	err := row.Scan(&has_members)
	return has_members, err
}

const listActiveMembersByTeam = `-- name: ListActiveMembersByTeam :many
SELECT id, team_id, player_id, role, jersey_number, status, joined_at, left_at, notes, created_at, updated_at, organization_id
FROM   team_memberships
WHERE  team_id         = $1
  AND  organization_id = $2
  AND  status          = 'active'
ORDER  BY joined_at ASC
`

type ListActiveMembersByTeamParams struct {
	TeamID         pgtype.UUID `json:"team_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Returns all currently active members of a team ordered by join date.
// Excludes historical (released, transferred, inactive) memberships.
func (q *Queries) ListActiveMembersByTeam(ctx context.Context, arg ListActiveMembersByTeamParams) ([]TeamMembership, error) {
	rows, err := q.db.Query(ctx, listActiveMembersByTeam, arg.TeamID, arg.OrganizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamMembership{}
	for rows.Next() {
		var i TeamMembership
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.PlayerID,
			&i.Role,
			&i.JerseyNumber,
			&i.Status,
			&i.JoinedAt,
			&i.LeftAt,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrganizationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMembership = `-- name: RemoveMembership :one
UPDATE team_memberships
SET    status     = 'released',
       left_at    = NOW(),
       updated_at = NOW()
WHERE  id              = $1
  AND  team_id         = $2
  AND  organization_id = $3
  AND  status          = 'active'
RETURNING id, team_id, player_id, role, jersey_number, status, joined_at, left_at, notes, created_at, updated_at, organization_id
`

type RemoveMembershipParams struct {
	ID             pgtype.UUID `json:"id"`
	TeamID         pgtype.UUID `json:"team_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Soft-removes by setting status = 'released' and left_at = NOW().
// Scoped by id, team_id, and organization_id to prevent cross-team or
// cross-org removal. Only active memberships are affected; returns no rows
// if the membership is already removed or belongs to a different team/org.
func (q *Queries) RemoveMembership(ctx context.Context, arg RemoveMembershipParams) (TeamMembership, error) {
	row := q.db.QueryRow(ctx, removeMembership, arg.ID, arg.TeamID, arg.OrganizationID)
	var i TeamMembership
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.PlayerID,
		&i.Role,
		&i.JerseyNumber,
		&i.Status,
		&i.JoinedAt,
		&i.LeftAt,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrganizationID,
	)
	return i, err
}
