// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTeamByID = `-- name: GetTeamByID :one

SELECT id, organization_id, name, short_name, slug, description, logo_url, home_city, home_venue, founded_year, primary_color, secondary_color, status, metadata, created_at, updated_at
FROM   teams
WHERE  id              = $1
  AND  organization_id = $2
LIMIT  1
`

type GetTeamByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Teams queries
// organization_id is always required to enforce tenant isolation.
func (q *Queries) GetTeamByID(ctx context.Context, arg GetTeamByIDParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, arg.ID, arg.OrganizationID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ShortName,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.HomeCity,
		&i.HomeVenue,
		&i.FoundedYear,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamBySlug = `-- name: GetTeamBySlug :one
SELECT id, organization_id, name, short_name, slug, description, logo_url, home_city, home_venue, founded_year, primary_color, secondary_color, status, metadata, created_at, updated_at
FROM   teams
WHERE  slug            = $1
  AND  organization_id = $2
LIMIT  1
`

type GetTeamBySlugParams struct {
	Slug           string      `json:"slug"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetTeamBySlug(ctx context.Context, arg GetTeamBySlugParams) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamBySlug, arg.Slug, arg.OrganizationID)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.ShortName,
		&i.Slug,
		&i.Description,
		&i.LogoUrl,
		&i.HomeCity,
		&i.HomeVenue,
		&i.FoundedYear,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamsByOrganization = `-- name: ListTeamsByOrganization :many
SELECT id, organization_id, name, short_name, slug, description, logo_url, home_city, home_venue, founded_year, primary_color, secondary_color, status, metadata, created_at, updated_at
FROM   teams
WHERE  organization_id = $1
ORDER  BY name ASC
`

func (q *Queries) ListTeamsByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]Team, error) {
	rows, err := q.db.Query(ctx, listTeamsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Team{}
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.ShortName,
			&i.Slug,
			&i.Description,
			&i.LogoUrl,
			&i.HomeCity,
			&i.HomeVenue,
			&i.FoundedYear,
			&i.PrimaryColor,
			&i.SecondaryColor,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
