// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tournaments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTournamentByID = `-- name: GetTournamentByID :one

SELECT id, organization_id, name, slug, description, sport, format, participant_type, status, banner_url, prize_pool, currency, max_participants, min_participants, registration_opens_at, registration_closes_at, starts_at, ends_at, venue, city, country, rules, settings, created_by, created_at, updated_at
FROM   tournaments
WHERE  id              = $1
  AND  organization_id = $2
LIMIT  1
`

type GetTournamentByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

// Tournaments queries
// organization_id is always required to enforce tenant isolation.
func (q *Queries) GetTournamentByID(ctx context.Context, arg GetTournamentByIDParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, getTournamentByID, arg.ID, arg.OrganizationID)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Sport,
		&i.Format,
		&i.ParticipantType,
		&i.Status,
		&i.BannerUrl,
		&i.PrizePool,
		&i.Currency,
		&i.MaxParticipants,
		&i.MinParticipants,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.StartsAt,
		&i.EndsAt,
		&i.Venue,
		&i.City,
		&i.Country,
		&i.Rules,
		&i.Settings,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTournamentBySlug = `-- name: GetTournamentBySlug :one
SELECT id, organization_id, name, slug, description, sport, format, participant_type, status, banner_url, prize_pool, currency, max_participants, min_participants, registration_opens_at, registration_closes_at, starts_at, ends_at, venue, city, country, rules, settings, created_by, created_at, updated_at
FROM   tournaments
WHERE  slug            = $1
  AND  organization_id = $2
LIMIT  1
`

type GetTournamentBySlugParams struct {
	Slug           string      `json:"slug"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetTournamentBySlug(ctx context.Context, arg GetTournamentBySlugParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, getTournamentBySlug, arg.Slug, arg.OrganizationID)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Sport,
		&i.Format,
		&i.ParticipantType,
		&i.Status,
		&i.BannerUrl,
		&i.PrizePool,
		&i.Currency,
		&i.MaxParticipants,
		&i.MinParticipants,
		&i.RegistrationOpensAt,
		&i.RegistrationClosesAt,
		&i.StartsAt,
		&i.EndsAt,
		&i.Venue,
		&i.City,
		&i.Country,
		&i.Rules,
		&i.Settings,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTournamentsByOrganization = `-- name: ListTournamentsByOrganization :many
SELECT id, organization_id, name, slug, description, sport, format, participant_type, status, banner_url, prize_pool, currency, max_participants, min_participants, registration_opens_at, registration_closes_at, starts_at, ends_at, venue, city, country, rules, settings, created_by, created_at, updated_at
FROM   tournaments
WHERE  organization_id = $1
ORDER  BY created_at DESC
`

func (q *Queries) ListTournamentsByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]Tournament, error) {
	rows, err := q.db.Query(ctx, listTournamentsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tournament{}
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.Sport,
			&i.Format,
			&i.ParticipantType,
			&i.Status,
			&i.BannerUrl,
			&i.PrizePool,
			&i.Currency,
			&i.MaxParticipants,
			&i.MinParticipants,
			&i.RegistrationOpensAt,
			&i.RegistrationClosesAt,
			&i.StartsAt,
			&i.EndsAt,
			&i.Venue,
			&i.City,
			&i.Country,
			&i.Rules,
			&i.Settings,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
