// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tournament_registrations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveRegistrations = `-- name: CountActiveRegistrations :one
SELECT COUNT(*)
FROM   tournament_registrations
WHERE  tournament_id = $1
  AND  status        IN ('pending', 'approved')
`

// Counts pending + approved registrations against max_participants capacity.
// Withdrawn, rejected, and disqualified registrations do not count.
func (q *Queries) CountActiveRegistrations(ctx context.Context, tournamentID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRegistrations, tournamentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRegistrationsByTournament = `-- name: CountRegistrationsByTournament :one
SELECT COUNT(*)
FROM   tournament_registrations
WHERE  tournament_id = $1
  AND  ($2::text IS NULL OR status::text = $2)
`

type CountRegistrationsByTournamentParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	StatusFilter *string     `json:"status_filter"`
}

// Total count matching the same filters as ListRegistrationsByTournamentPaginated.
func (q *Queries) CountRegistrationsByTournament(ctx context.Context, arg CountRegistrationsByTournamentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRegistrationsByTournament, arg.TournamentID, arg.StatusFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRegistration = `-- name: CreateRegistration :one
INSERT INTO tournament_registrations (
    tournament_id, organization_id, team_id, player_id,
    registered_by, notes
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tournament_id, organization_id, team_id, player_id, seed_number, status, registered_by, registered_at, approved_by, approved_at, notes, metadata, created_at, updated_at
`

type CreateRegistrationParams struct {
	TournamentID   pgtype.UUID `json:"tournament_id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	TeamID         pgtype.UUID `json:"team_id"`
	PlayerID       pgtype.UUID `json:"player_id"`
	RegisteredBy   pgtype.UUID `json:"registered_by"`
	Notes          *string     `json:"notes"`
}

// Inserts a new pending registration. The partial unique index
// uq_treg_tournament_team prevents duplicate (tournament, team) pairs.
func (q *Queries) CreateRegistration(ctx context.Context, arg CreateRegistrationParams) (TournamentRegistration, error) {
	row := q.db.QueryRow(ctx, createRegistration,
		arg.TournamentID,
		arg.OrganizationID,
		arg.TeamID,
		arg.PlayerID,
		arg.RegisteredBy,
		arg.Notes,
	)
	var i TournamentRegistration
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OrganizationID,
		&i.TeamID,
		&i.PlayerID,
		&i.SeedNumber,
		&i.Status,
		&i.RegisteredBy,
		&i.RegisteredAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovedRegistrationByPlayer = `-- name: GetApprovedRegistrationByPlayer :one
SELECT id
FROM   tournament_registrations
WHERE  tournament_id = $1
  AND  player_id     = $2
  AND  status        = 'approved'
LIMIT  1
`

type GetApprovedRegistrationByPlayerParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	PlayerID     pgtype.UUID `json:"player_id"`
}

// Used by the matches module to verify a player has an approved registration
// before being assigned as a match participant.
func (q *Queries) GetApprovedRegistrationByPlayer(ctx context.Context, arg GetApprovedRegistrationByPlayerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getApprovedRegistrationByPlayer, arg.TournamentID, arg.PlayerID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getApprovedRegistrationByTeam = `-- name: GetApprovedRegistrationByTeam :one
SELECT id
FROM   tournament_registrations
WHERE  tournament_id = $1
  AND  team_id       = $2
  AND  status        = 'approved'
LIMIT  1
`

type GetApprovedRegistrationByTeamParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	TeamID       pgtype.UUID `json:"team_id"`
}

// Used by the matches module to verify a team has an approved registration
// before being assigned as a match participant.
func (q *Queries) GetApprovedRegistrationByTeam(ctx context.Context, arg GetApprovedRegistrationByTeamParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getApprovedRegistrationByTeam, arg.TournamentID, arg.TeamID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getRegistrationByID = `-- name: GetRegistrationByID :one

SELECT id, tournament_id, organization_id, team_id, player_id, seed_number, status, registered_by, registered_at, approved_by, approved_at, notes, metadata, created_at, updated_at
FROM   tournament_registrations
WHERE  id            = $1
  AND  tournament_id = $2
LIMIT  1
`

type GetRegistrationByIDParams struct {
	ID           pgtype.UUID `json:"id"`
	TournamentID pgtype.UUID `json:"tournament_id"`
}

// Tournament registration queries
// tournament_id always required; organization_id is the registrant's org.
// Fetches a single registration scoped to its tournament.
func (q *Queries) GetRegistrationByID(ctx context.Context, arg GetRegistrationByIDParams) (TournamentRegistration, error) {
	row := q.db.QueryRow(ctx, getRegistrationByID, arg.ID, arg.TournamentID)
	var i TournamentRegistration
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OrganizationID,
		&i.TeamID,
		&i.PlayerID,
		&i.SeedNumber,
		&i.Status,
		&i.RegisteredBy,
		&i.RegisteredAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistrationByPlayer = `-- name: GetRegistrationByPlayer :one
SELECT id, tournament_id, organization_id, team_id, player_id, seed_number, status, registered_by, registered_at, approved_by, approved_at, notes, metadata, created_at, updated_at
FROM   tournament_registrations
WHERE  tournament_id = $1
  AND  player_id     = $2
LIMIT  1
`

type GetRegistrationByPlayerParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	PlayerID     pgtype.UUID `json:"player_id"`
}

// Returns an existing registration for the given (tournament, player) pair,
// regardless of status. Used to enforce Rule 4: no duplicate registrations.
func (q *Queries) GetRegistrationByPlayer(ctx context.Context, arg GetRegistrationByPlayerParams) (TournamentRegistration, error) {
	row := q.db.QueryRow(ctx, getRegistrationByPlayer, arg.TournamentID, arg.PlayerID)
	var i TournamentRegistration
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OrganizationID,
		&i.TeamID,
		&i.PlayerID,
		&i.SeedNumber,
		&i.Status,
		&i.RegisteredBy,
		&i.RegisteredAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRegistrationByTeam = `-- name: GetRegistrationByTeam :one
SELECT id, tournament_id, organization_id, team_id, player_id, seed_number, status, registered_by, registered_at, approved_by, approved_at, notes, metadata, created_at, updated_at
FROM   tournament_registrations
WHERE  tournament_id = $1
  AND  team_id       = $2
LIMIT  1
`

type GetRegistrationByTeamParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	TeamID       pgtype.UUID `json:"team_id"`
}

// Returns an existing registration for the given (tournament, team) pair,
// regardless of status. Used to enforce Rule 4: no duplicate registrations.
func (q *Queries) GetRegistrationByTeam(ctx context.Context, arg GetRegistrationByTeamParams) (TournamentRegistration, error) {
	row := q.db.QueryRow(ctx, getRegistrationByTeam, arg.TournamentID, arg.TeamID)
	var i TournamentRegistration
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OrganizationID,
		&i.TeamID,
		&i.PlayerID,
		&i.SeedNumber,
		&i.Status,
		&i.RegisteredBy,
		&i.RegisteredAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovedRegistrationsForStandings = `-- name: ListApprovedRegistrationsForStandings :many
SELECT team_id, player_id, seed_number, registered_at
FROM   tournament_registrations
WHERE  tournament_id = $1
  AND  status        = 'approved'
ORDER  BY registered_at ASC
`

type ListApprovedRegistrationsForStandingsRow struct {
	TeamID       pgtype.UUID        `json:"team_id"`
	PlayerID     pgtype.UUID        `json:"player_id"`
	SeedNumber   *int16             `json:"seed_number"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}

// Returns all approved registrations for a tournament for standings computation.
// Does NOT filter by organization_id: tournament_registrations.organization_id
// is the registrant's org (not the host org), and cross-org registrations are
// valid for multi-club tournaments.  The host tournament is already verified by
// the caller via tournament_id + host organization_id before this query runs.
// Ordered by registered_at ASC so the standings engine uses registration time
// as the final deterministic tiebreaker without additional sorting.
func (q *Queries) ListApprovedRegistrationsForStandings(ctx context.Context, tournamentID pgtype.UUID) ([]ListApprovedRegistrationsForStandingsRow, error) {
	rows, err := q.db.Query(ctx, listApprovedRegistrationsForStandings, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApprovedRegistrationsForStandingsRow{}
	for rows.Next() {
		var i ListApprovedRegistrationsForStandingsRow
		if err := rows.Scan(
			&i.TeamID,
			&i.PlayerID,
			&i.SeedNumber,
			&i.RegisteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistrationsByTournamentPaginated = `-- name: ListRegistrationsByTournamentPaginated :many
SELECT id, tournament_id, organization_id, team_id, player_id, seed_number, status, registered_by, registered_at, approved_by, approved_at, notes, metadata, created_at, updated_at
FROM   tournament_registrations
WHERE  tournament_id = $1
  AND  ($2::text IS NULL OR status::text = $2)
ORDER  BY registered_at ASC
LIMIT  $4
OFFSET $3
`

type ListRegistrationsByTournamentPaginatedParams struct {
	TournamentID pgtype.UUID `json:"tournament_id"`
	StatusFilter *string     `json:"status_filter"`
	PageOffset   int32       `json:"page_offset"`
	PageLimit    int32       `json:"page_limit"`
}

// Paginated listing of all registrations for a tournament.
// Optional status filter; no status is excluded by default.
func (q *Queries) ListRegistrationsByTournamentPaginated(ctx context.Context, arg ListRegistrationsByTournamentPaginatedParams) ([]TournamentRegistration, error) {
	rows, err := q.db.Query(ctx, listRegistrationsByTournamentPaginated,
		arg.TournamentID,
		arg.StatusFilter,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TournamentRegistration{}
	for rows.Next() {
		var i TournamentRegistration
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.OrganizationID,
			&i.TeamID,
			&i.PlayerID,
			&i.SeedNumber,
			&i.Status,
			&i.RegisteredBy,
			&i.RegisteredAt,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.Notes,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTournamentForUpdate = `-- name: LockTournamentForUpdate :one
SELECT id
FROM   tournaments
WHERE  id = $1
FOR    UPDATE
`

// Acquires an exclusive row-level lock on the tournament row inside a
// transaction. All concurrent registrations for the same tournament block
// here until the holding transaction commits or rolls back, preventing
// concurrent reads of the same capacity count from racing to insert.
func (q *Queries) LockTournamentForUpdate(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockTournamentForUpdate, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const updateRegistration = `-- name: UpdateRegistration :one
UPDATE tournament_registrations
SET    status      = $3,
       seed_number = $4,
       notes       = $5,
       approved_by = $6,
       approved_at = CASE WHEN $7::TIMESTAMPTZ IS NOT NULL THEN GREATEST($7::TIMESTAMPTZ, registered_at) ELSE NULL END,
       updated_at  = NOW()
WHERE  id            = $1
  AND  tournament_id = $2
RETURNING id, tournament_id, organization_id, team_id, player_id, seed_number, status, registered_by, registered_at, approved_by, approved_at, notes, metadata, created_at, updated_at
`

type UpdateRegistrationParams struct {
	ID           pgtype.UUID        `json:"id"`
	TournamentID pgtype.UUID        `json:"tournament_id"`
	Status       RegistrationStatus `json:"status"`
	SeedNumber   *int16             `json:"seed_number"`
	Notes        *string            `json:"notes"`
	ApprovedBy   pgtype.UUID        `json:"approved_by"`
	Column7      pgtype.Timestamptz `json:"column_7"`
}

// Updates mutable fields. Service layer applies partial request over
// current state. approved_by and approved_at are set on status=approved.
func (q *Queries) UpdateRegistration(ctx context.Context, arg UpdateRegistrationParams) (TournamentRegistration, error) {
	row := q.db.QueryRow(ctx, updateRegistration,
		arg.ID,
		arg.TournamentID,
		arg.Status,
		arg.SeedNumber,
		arg.Notes,
		arg.ApprovedBy,
		arg.Column7,
	)
	var i TournamentRegistration
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OrganizationID,
		&i.TeamID,
		&i.PlayerID,
		&i.SeedNumber,
		&i.Status,
		&i.RegisteredBy,
		&i.RegisteredAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const withdrawRegistration = `-- name: WithdrawRegistration :one
UPDATE tournament_registrations
SET    status     = 'withdrawn',
       updated_at = NOW()
WHERE  id            = $1
  AND  tournament_id = $2
  AND  status        IN ('pending', 'approved')
RETURNING id, tournament_id, organization_id, team_id, player_id, seed_number, status, registered_by, registered_at, approved_by, approved_at, notes, metadata, created_at, updated_at
`

type WithdrawRegistrationParams struct {
	ID           pgtype.UUID `json:"id"`
	TournamentID pgtype.UUID `json:"tournament_id"`
}

// Soft-removes by setting status = 'withdrawn'.
// Only acts on pending or approved registrations; returns no rows if already
// in a terminal state (rejected, withdrawn, disqualified).
func (q *Queries) WithdrawRegistration(ctx context.Context, arg WithdrawRegistrationParams) (TournamentRegistration, error) {
	row := q.db.QueryRow(ctx, withdrawRegistration, arg.ID, arg.TournamentID)
	var i TournamentRegistration
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OrganizationID,
		&i.TeamID,
		&i.PlayerID,
		&i.SeedNumber,
		&i.Status,
		&i.RegisteredBy,
		&i.RegisteredAt,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.Notes,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
