// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, first_name, last_name, phone, avatar_url, date_of_birth, gender, status, email_verified_at, last_login_at, last_login_ip, created_at, updated_at
FROM   users
WHERE  email = $1
LIMIT  1
`

// Used by the authentication flow for login.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, email, username, password_hash, first_name, last_name, phone, avatar_url, date_of_birth, gender, status, email_verified_at, last_login_at, last_login_ip, created_at, updated_at
FROM   users
WHERE  id = $1
LIMIT  1
`

// Users queries
// Passwords are handled outside generated code; only safe read projections here.
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, first_name, last_name, phone, avatar_url, date_of_birth, gender, status, email_verified_at, last_login_at, last_login_ip, created_at, updated_at
FROM   users
WHERE  username = $1
LIMIT  1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, username, password_hash, first_name, last_name, phone, avatar_url, date_of_birth, gender, status, email_verified_at, last_login_at, last_login_ip, created_at, updated_at
FROM   users
ORDER  BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.AvatarUrl,
			&i.DateOfBirth,
			&i.Gender,
			&i.Status,
			&i.EmailVerifiedAt,
			&i.LastLoginAt,
			&i.LastLoginIp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
