// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash, first_name, last_name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, username, password_hash, first_name, last_name, phone, avatar_url, date_of_birth, gender, status, email_verified_at, last_login_at, last_login_ip, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
}

// Inserts a new platform user. status defaults to pending_verification;
// all nullable profile columns are left NULL until the user fills them in.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, first_name, last_name, phone, avatar_url, date_of_birth, gender, status, email_verified_at, last_login_at, last_login_ip, created_at, updated_at
FROM   users
WHERE  email = $1
LIMIT  1
`

// Used by the authentication flow for login.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one

SELECT id, email, username, password_hash, first_name, last_name, phone, avatar_url, date_of_birth, gender, status, email_verified_at, last_login_at, last_login_ip, created_at, updated_at
FROM   users
WHERE  id = $1
LIMIT  1
`

// Users queries
// Passwords are handled outside generated code; only safe read projections here.
func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, first_name, last_name, phone, avatar_url, date_of_birth, gender, status, email_verified_at, last_login_at, last_login_ip, created_at, updated_at
FROM   users
WHERE  username = $1
LIMIT  1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.AvatarUrl,
		&i.DateOfBirth,
		&i.Gender,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.LastLoginAt,
		&i.LastLoginIp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, username, password_hash, first_name, last_name, phone, avatar_url, date_of_birth, gender, status, email_verified_at, last_login_at, last_login_ip, created_at, updated_at
FROM   users
ORDER  BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.AvatarUrl,
			&i.DateOfBirth,
			&i.Gender,
			&i.Status,
			&i.EmailVerifiedAt,
			&i.LastLoginAt,
			&i.LastLoginIp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET    password_hash = $1,
       updated_at    = NOW()
WHERE  id = $2
`

type UpdateUserPasswordHashParams struct {
	PasswordHash string      `json:"password_hash"`
	ID           pgtype.UUID `json:"id"`
}

// Replaces the stored bcrypt hash. Called exclusively by ResetPasswordTransaction
// inside a FOR UPDATE token-locked transaction so the password update is atomic
// with token consumption and session revocation.
func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET    email_verified_at = NOW(),
       status            = 'active',
       updated_at        = NOW()
WHERE  id     = $1
  AND  status = 'pending_verification'
`

// Activates the account after the user clicks the verification link.
// The AND status = 'pending_verification' guard makes the call idempotent:
// if the account is already active (e.g. concurrent verification), it is a
// safe no-op.
func (q *Queries) VerifyUserEmail(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
