// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimWebhookDeliveriesForDelivery = `-- name: ClaimWebhookDeliveriesForDelivery :many
UPDATE webhook_deliveries wd
SET last_attempted_at = NOW(),
    lease_expires_at  = NOW() + INTERVAL '5 minutes',
    attempt_count     = wd.attempt_count + 1
WHERE wd.id IN (
    SELECT q.id
    FROM   webhook_deliveries q
    WHERE  q.sent_at            IS NULL
      AND  q.failed_permanently = FALSE
      AND  q.attempt_count      < $1
      AND  (q.lease_expires_at  IS NULL OR q.lease_expires_at < NOW())
    ORDER  BY q.last_attempted_at ASC NULLS FIRST, q.created_at ASC
    LIMIT  $2
    FOR    UPDATE SKIP LOCKED
)
RETURNING id, organization_id, endpoint_id, outbox_id, event_type, entity_type, entity_id, payload, attempt_count, last_attempted_at, lease_expires_at, sent_at, failed_permanently, created_at
`

type ClaimWebhookDeliveriesForDeliveryParams struct {
	MaxAttempts int32 `json:"max_attempts"`
	BatchSize   int32 `json:"batch_size"`
}

// Claims up to batch_size pending webhook deliveries using FOR UPDATE SKIP LOCKED.
// Increments attempt_count and sets a 5-minute soft lease.
// Only rows with attempt_count < max_attempts are eligible.
func (q *Queries) ClaimWebhookDeliveriesForDelivery(ctx context.Context, arg ClaimWebhookDeliveriesForDeliveryParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, claimWebhookDeliveriesForDelivery, arg.MaxAttempts, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.EndpointID,
			&i.OutboxID,
			&i.EventType,
			&i.EntityType,
			&i.EntityID,
			&i.Payload,
			&i.AttemptCount,
			&i.LastAttemptedAt,
			&i.LeaseExpiresAt,
			&i.SentAt,
			&i.FailedPermanently,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one

INSERT INTO webhook_deliveries (
    organization_id,
    endpoint_id,
    outbox_id,
    event_type,
    entity_type,
    entity_id,
    payload
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (outbox_id, endpoint_id) DO NOTHING
RETURNING id, organization_id, endpoint_id, outbox_id, event_type, entity_type, entity_id, payload, attempt_count, last_attempted_at, lease_expires_at, sent_at, failed_permanently, created_at
`

type CreateWebhookDeliveryParams struct {
	OrganizationID pgtype.UUID           `json:"organization_id"`
	EndpointID     pgtype.UUID           `json:"endpoint_id"`
	OutboxID       pgtype.UUID           `json:"outbox_id"`
	EventType      NotificationEventType `json:"event_type"`
	EntityType     string                `json:"entity_type"`
	EntityID       pgtype.UUID           `json:"entity_id"`
	Payload        []byte                `json:"payload"`
}

// =============================================================================
// DELIVERY QUERIES (used by internal/webhookworker and DrainOutbox)
// =============================================================================
// Written by DrainOutbox for each active webhook endpoint in the org.
// ON CONFLICT DO NOTHING makes retries of DrainOutbox idempotent.
func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.OrganizationID,
		arg.EndpointID,
		arg.OutboxID,
		arg.EventType,
		arg.EntityType,
		arg.EntityID,
		arg.Payload,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.EndpointID,
		&i.OutboxID,
		&i.EventType,
		&i.EntityType,
		&i.EntityID,
		&i.Payload,
		&i.AttemptCount,
		&i.LastAttemptedAt,
		&i.LeaseExpiresAt,
		&i.SentAt,
		&i.FailedPermanently,
		&i.CreatedAt,
	)
	return i, err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one



INSERT INTO webhook_endpoints (
    organization_id,
    url,
    secret_ciphertext,
    description,
    active,
    created_by
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, organization_id, url, secret_ciphertext, description, active, created_by, created_at, updated_at
`

type CreateWebhookEndpointParams struct {
	OrganizationID   pgtype.UUID `json:"organization_id"`
	Url              string      `json:"url"`
	SecretCiphertext []byte      `json:"secret_ciphertext"`
	Description      *string     `json:"description"`
	Active           bool        `json:"active"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

// Webhook queries
// All endpoint queries are scoped by organization_id.
// Delivery queries are used only by WebhookWorker and DrainOutbox.
// =============================================================================
// ENDPOINT QUERIES (used by internal/webhooks)
// =============================================================================
func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.OrganizationID,
		arg.Url,
		arg.SecretCiphertext,
		arg.Description,
		arg.Active,
		arg.CreatedBy,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Url,
		&i.SecretCiphertext,
		&i.Description,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldWebhookDeliveries = `-- name: DeleteOldWebhookDeliveries :exec
DELETE FROM webhook_deliveries
WHERE sent_at IS NOT NULL
  AND sent_at < $1
`

// Deletes delivered webhook_deliveries rows older than the retention cutoff.
// Called by the cleanup scheduler to prevent unbounded table growth.
func (q *Queries) DeleteOldWebhookDeliveries(ctx context.Context, olderThan pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteOldWebhookDeliveries, olderThan)
	return err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :execrows
DELETE FROM webhook_endpoints
WHERE  id              = $1
  AND  organization_id = $2
`

type DeleteWebhookEndpointParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, arg DeleteWebhookEndpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWebhookEndpoint, arg.ID, arg.OrganizationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveWebhookEndpointsForOrg = `-- name: GetActiveWebhookEndpointsForOrg :many
SELECT id, organization_id, url, secret_ciphertext, description, active, created_by, created_at, updated_at
FROM   webhook_endpoints
WHERE  organization_id = $1
  AND  active          = TRUE
`

// Returns all active endpoints for an organization.
// Called by DrainOutbox to determine the webhook fan-out set.
func (q *Queries) GetActiveWebhookEndpointsForOrg(ctx context.Context, organizationID pgtype.UUID) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, getActiveWebhookEndpointsForOrg, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Url,
			&i.SecretCiphertext,
			&i.Description,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebhookEndpointByID = `-- name: GetWebhookEndpointByID :one
SELECT id, organization_id, url, secret_ciphertext, description, active, created_by, created_at, updated_at
FROM   webhook_endpoints
WHERE  id              = $1
  AND  organization_id = $2
LIMIT  1
`

type GetWebhookEndpointByIDParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) GetWebhookEndpointByID(ctx context.Context, arg GetWebhookEndpointByIDParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointByID, arg.ID, arg.OrganizationID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Url,
		&i.SecretCiphertext,
		&i.Description,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookEndpointForDelivery = `-- name: GetWebhookEndpointForDelivery :one
SELECT e.id, e.organization_id, e.url, e.secret_ciphertext, e.description, e.active, e.created_by, e.created_at, e.updated_at
FROM   webhook_endpoints e
       JOIN webhook_deliveries d ON d.endpoint_id = e.id
WHERE  d.id = $1
LIMIT  1
`

// Fetches the endpoint referenced by a delivery row (worker needs URL + secret).
func (q *Queries) GetWebhookEndpointForDelivery(ctx context.Context, id pgtype.UUID) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointForDelivery, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Url,
		&i.SecretCiphertext,
		&i.Description,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, organization_id, url, secret_ciphertext, description, active, created_by, created_at, updated_at
FROM   webhook_endpoints
WHERE  organization_id = $1
ORDER  BY created_at DESC
`

func (q *Queries) ListWebhookEndpoints(ctx context.Context, organizationID pgtype.UUID) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpoints, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Url,
			&i.SecretCiphertext,
			&i.Description,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordWebhookDeliveryFailure = `-- name: RecordWebhookDeliveryFailure :exec
UPDATE webhook_deliveries
SET failed_permanently = $1,
    lease_expires_at   = $2
WHERE id = $3
`

type RecordWebhookDeliveryFailureParams struct {
	FailedPermanently bool               `json:"failed_permanently"`
	NextAttemptAt     pgtype.Timestamptz `json:"next_attempt_at"`
	ID                pgtype.UUID        `json:"id"`
}

// Records a failed delivery. failed_permanently = TRUE when max_attempts exhausted.
// lease_expires_at is advanced to next_attempt_at so the claim query skips
// this row until the retry window elapses.
func (q *Queries) RecordWebhookDeliveryFailure(ctx context.Context, arg RecordWebhookDeliveryFailureParams) error {
	_, err := q.db.Exec(ctx, recordWebhookDeliveryFailure, arg.FailedPermanently, arg.NextAttemptAt, arg.ID)
	return err
}

const recordWebhookDeliverySuccess = `-- name: RecordWebhookDeliverySuccess :exec
UPDATE webhook_deliveries
SET sent_at = NOW()
WHERE id      = $1
  AND sent_at IS NULL
`

// Marks a webhook delivery as successfully delivered.
// sent_at IS NULL guard: idempotent against double-recording on worker crash.
func (q *Queries) RecordWebhookDeliverySuccess(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordWebhookDeliverySuccess, id)
	return err
}

const updateWebhookEndpointActive = `-- name: UpdateWebhookEndpointActive :one
UPDATE webhook_endpoints
SET    active     = $3,
       updated_at = NOW()
WHERE  id              = $1
  AND  organization_id = $2
RETURNING id, organization_id, url, secret_ciphertext, description, active, created_by, created_at, updated_at
`

type UpdateWebhookEndpointActiveParams struct {
	ID             pgtype.UUID `json:"id"`
	OrganizationID pgtype.UUID `json:"organization_id"`
	Active         bool        `json:"active"`
}

// Toggle active/inactive without deleting. Returns updated row.
func (q *Queries) UpdateWebhookEndpointActive(ctx context.Context, arg UpdateWebhookEndpointActiveParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, updateWebhookEndpointActive, arg.ID, arg.OrganizationID, arg.Active)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Url,
		&i.SecretCiphertext,
		&i.Description,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
