package organizations

// This package uses db.Organization (generated by sqlc) as the primary domain
// struct — no additional domain model is needed at this layer.
//
// All conversion between db.Organization and the HTTP Response type is done
// in service.go via orgToResponse().
